apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ollama
  namespace: default
spec:
  driftDetection:
    mode: enabled
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s-labs.github.io/helm-charts
      chart: app-template
      version: 4.6.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        defaultContainerOptions:
          resources:
            requests:
              cpu: 1
              memory: 2Gi
            limits:
              cpu: 3
              memory: 8Gi
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            fsGroup: 3001
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups: [ 568, 911, 1000, 1001 ]
          tolerations:
          - key: "arm"
            operator: "Exists"
        containers:
          main:
            image:
              # renovate: repository=docker.io/ollama/ollama
              repository: ollama/ollama
              tag: 0.21.2
            securityContext:
              runAsUser: 1000
              runAsGroup: 3001
            env:
              TZ: "America/New_York"
              OLLAMA_PORT: &port "11434"
              OLLAMA_MAX_LOADED_MODELS: "1"
              OLLAMA_MAX_QUEUE: "5"
              OLLAMA_NUM_PARALLEL: "1"
              OLLAMA_NO_CLOUD: "true"
              OLLAMA_MODELS: "/app/data/models"
              OLLAMA_NOHISTORY: "true"
              OLLAMA_NOPRUNE: "true"
    service:
      main:
        controller: main
        type: ClusterIP
        ports:
          http:
            port: *port

    ingress:
      main:
        className: 'traefik'
        annotations:
          kubernetes.io/ingress.class: traefik
          traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
          traefik.ingress.kubernetes.io/router.middlewares: "network-system-authentik@kubernetescrd"
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: AI
          gethomepage.dev/icon: ollama.svg
          gethomepage.dev/name: Ollama
          gethomepage.dev/description: Ollama is a self-hosted inference engine that allows you to run large language models locally.
        hosts:
        - host: &host "ollama.homelab.heyser.xyz"
          paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: http
        tls:
        - hosts:
          - *host
          secretName: ollama-homelab-heyser-xyz-tls
      api:
        className: 'traefik'
        annotations:
          kubernetes.io/ingress.class: traefik
          traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
          # traefik.ingress.kubernetes.io/router.middlewares: "network-system-authentik@kubernetescrd"
          # gethomepage.dev/enabled: "true"
          # gethomepage.dev/group: AI
          # gethomepage.dev/icon: ollama.svg
          # gethomepage.dev/name: Ollama
          # gethomepage.dev/description: Ollama is a self-hosted inference engine that allows you to run large language models locally.
        hosts:
        - host: *host
          paths:
          - path: /api
            pathType: Prefix
            service:
              identifier: main
              port: http
        tls:
        - hosts:
          - *host
          secretName: ollama-homelab-heyser-xyz-tls

    # route:
    #   main:
    #     enabled: true
    #     kind: HTTPRoute
    #     parentRefs:
    #     - group: gateway.networking.k8s.io
    #       kind: Gateway
    #       name: traefik-gateway
    #       namespace: network-system
    #     hostnames:
    #     - *host
    #     rules:
    #     - matches:
    #       - path:
    #           type: PathPrefix
    #           value: /
    #       backendRefs:
    #       - kind: Service
    #         name: audiobookshelf
    #         port: *port
    #       timeouts:
    #         backendRequest: 10s
    #         request: 30s

    persistence:
      config:
        existingClaim: ollama-config
        advancedMounts:
          main:
            main:
            - path: "/app/data"
