apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prowlarr-tailscale
spec:
  defaultBackend:
    service:
      name: prowlarr
      port:
        number: 9696
  ingressClassName: tailscale
  tls:
  - hosts:
    - prowlarr
