apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: prowlarr-vpn
spec:
  config: '{ 
    "plugins": [
        {
          "name": "vpnnet1",
          "type": "bridge",
          "bridge": "vpnbr",
          "ipam": {
            "type": "host-local",
            "subnet": "10.99.0.0/18",
            "rangeStart": "10.99.1.20",
            "rangeEnd": "10.99.1.29",
            "gateway": "10.99.0.1",
            "routes": [
              { "dst": "0.0.0.0/0" }
            ]
          }
        },
        {
          "type": "sbr"
        }
      ]
    }'
---
