apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-nfs
  namespace: storage-system
spec:
  driftDetection:
    mode: enabled
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
      chart: csi-driver-nfs
      version: 4.12.1
      sourceRef:
        kind: HelmRepository
        name: csi-nfs
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      replicas: 3
      strategyType: RollingUpdate
      defaultOnDeletePolicy: retain
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
      - key: node-role.kubernetes.io/etcd
        operator: Exists
      - key: node-role.kubernetes.io/master
        operator: Exists
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - csi-nfs
            topologyKey: "kubernetes.io/hostname"
    node:
      maxUnavailable: 1
      tolerations:
      - operator: Exists
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
      - key: node-role.kubernetes.io/etcd
        operator: Exists
      - key: node-role.kubernetes.io/master
        operator: Exists
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - csi-nfs
            topologyKey: "kubernetes.io/hostname"
    externalSnapshotter:
      enabled: true
      controller:
        replicas: 2
      customResourceDefinitions:
        enabled: true
    storageClass:
      create: true
      name: nfs-dynamic-database
      annotations:
        storageclass.kubernetes.io/is-default-class: "false"
      parameters:
        server: "10.0.0.8"
        share: "/mnt/kracko/database"
        subdir: "${pvc.metadata.name}"
      reclaimPolicy: Retain
      volumeBindingMode: Immediate
      mountOptions:
      - "vers=4"
      - "minorversion=1"
      - "local_lock=posix"
      - "proto=tcp"
      - "noresvport"
      - "ac"
