apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: audiobookshelf
  namespace: default
spec:
  driftDetection:
    mode: enabled
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s-labs.github.io/helm-charts
      chart: app-template
      version: 4.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        defaultContainerOptions:
          resources:
            requests:
              cpu: 10m
              memory: 250Mi
            limits:
              memory: 2Gi
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            fsGroup: 3001
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups: [ 568, 911, 1000, 1001 ]
          tolerations:
          - key: "arm"
            operator: "Exists"
        containers:
          main:
            image:
              # renovate: repository=ghcr.io/advplyr/audiobookshelf
              repository: ghcr.io/advplyr/audiobookshelf
              tag: 2.31.0
            securityContext:
              runAsUser: 1000
              runAsGroup: 3001
            env:
              TZ: "America/New_York"
              AUDIOBOOKSHELF_UID: 1000
              AUDIOBOOKSHELF_GID: 3001
              CONFIG_PATH: /config
              METADATA_PATH: /config/metadata
    service:
      main:
        controller: main
        type: ClusterIP
        ports:
          http:
            port: 80

    ingress:
      main:
        className: 'traefik'
        annotations:
          kubernetes.io/ingress.class: traefik
          traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
          # traefik.ingress.kubernetes.io/router.middlewares: "network-system-authentik@kubernetescrd"
        hosts:
        - host: &host "audiobookshelf.homelab.heyser.xyz"
          paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: http
        tls:
        - hosts:
          - *host
          secretName: audiobookshelf-homelab-heyser-xyz-tls

    route:
      main:
        enabled: true
        kind: HTTPRoute
        parentRefs:
        - group: gateway.networking.k8s.io
          kind: Gateway
          name: traefik-gateway
          namespace: network-system
        hostnames:
        - *host
        rules:
        - matches:
          - path:
              type: PathPrefix
              value: /
          backendRefs:
          - kind: Service
            name: audiobookshelf
            port: 80
          timeouts:
            backendRequest: 10s
            request: 30s

    persistence:
      config:
        existingClaim: audiobookshelf-config
        advancedMounts:
          main:
            main:
            - path: "/config"
      media:
        existingClaim: audiobookshelf-media
      cache:
        advancedMounts:
          main:
            main:
            - path: "/.npm"
        type: emptyDir
