---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: audiobookshelf-tailscale
spec:
  defaultBackend:
    service:
      name: audiobookshelf
      port:
        number: 80
  ingressClassName: tailscale
  tls:
    - hosts:
        - audiobookshelf
