---
apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: ts-k8s-pod-cidrs
spec:
  replicas: 2
  hostnamePrefix: ts-k8s-pod-cidrs
  proxyClass: ts-proxyclass
  tags:
  - tag:k8s
  subnetRouter:
    advertiseRoutes:
    - "10.254.0.0/16"
    - "10.255.0.0/16"
---
apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: ts-k8s-home-cidrs
spec:
  replicas: 2
  hostnamePrefix: ts-k8s-home-cidrs
  proxyClass: ts-proxyclass
  tags:
  - tag:k8s
  subnetRouter:
    advertiseRoutes:
    - "10.0.0.0/18"
    - "10.0.64.0/24"
    - "10.98.0.0/18"
    - "192.168.88.0/24"
---
apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: ts-k8s-exit-node
spec:
  replicas: 3
  proxyClass: ts-proxyclass
  hostnamePrefix: ts-k8s-exit-node
  tags:
  - tag:k8s
  exitNode: true
---
apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: ts-k8s-netflix
spec:
  replicas: 2
  hostnamePrefix: ts-k8s-netflix
  proxyClass: ts-proxyclass
  appConnector: {}
  tags:
  - tag:k8s
  - tag:app-netflix
---
apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: ts-k8s-hulu
spec:
  replicas: 2
  hostnamePrefix: ts-k8s-hulu
  proxyClass: ts-proxyclass
  appConnector: {}
  tags:
  - tag:k8s
  - tag:app-hulu
---
apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: ts-k8s-disneyplus
spec:
  replicas: 2
  hostnamePrefix: ts-k8s-disneyplus
  proxyClass: ts-proxyclass
  appConnector: {}
  tags:
  - tag:k8s
  - tag:app-disneyplus
---
apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: ts-k8s-homelab
spec:
  replicas: 2
  hostnamePrefix: ts-k8s-homelab
  proxyClass: ts-proxyclass
  appConnector: {}
  tags:
  - tag:k8s
  - tag:app-homelab
