apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: ts-proxyclass
spec:
  tailscale:
    acceptRoutes: true
  metrics:
    enable: true
  statefulSet:
    pod:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: tailscale.com/parent-resource
                operator: In
                values:
                - ts-proxygroup
            topologyKey: "kubernetes.io/hostname"
          - labelSelector:
              matchExpressions:
              - key: tailscale.com/parent-resource
                operator: In
                values:
                - ts-k8s-home-cidrs
            topologyKey: "kubernetes.io/hostname"
          - labelSelector:
              matchExpressions:
              - key: tailscale.com/parent-resource
                operator: In
                values:
                - ts-k8s-pod-cidrs
            topologyKey: "kubernetes.io/hostname"
          - labelSelector:
              matchExpressions:
              - key: tailscale.com/parent-resource
                operator: In
                values:
                - ts-k8s-disneyplus
            topologyKey: "kubernetes.io/hostname"
          - labelSelector:
              matchExpressions:
              - key: tailscale.com/parent-resource
                operator: In
                values:
                - ts-k8s-hulu
            topologyKey: "kubernetes.io/hostname"
          - labelSelector:
              matchExpressions:
              - key: tailscale.com/parent-resource
                operator: In
                values:
                - ts-k8s-netflix
            topologyKey: "kubernetes.io/hostname"
---
apiVersion: tailscale.com/v1alpha1
kind: ProxyGroup
metadata:
  name: ts-proxygroup
spec:
  type: egress
  replicas: 3
  hostnamePrefix: ts-proxygroup
  proxyClass: ts-proxyclass
