apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: ts-proxyclass
spec:
  tailscale:
    acceptRoutes: true
  metrics:
    enable: true
---
apiVersion: tailscale.com/v1alpha1
kind: ProxyGroup
metadata:
  name: ts-proxygroup
spec:
  type: egress
  replicas: 3
  hostnamePrefix: ts-proxygroup
  proxyClass: ts-proxyclass
