apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: ts-proxyclass
spec:
  tailscale:
    acceptRoutes: true
  metrics:
    enable: true
  statefulSet:
    pod:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: tailscale.com/parent-resource
                  operator: In
                  values:
                  - ts-k8s-home-cidrs
              topologyKey: "kubernetes.io/hostname"
          - weight: 99
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: tailscale.com/parent-resource
                  operator: In
                  values:
                  - ts-proxygroup
              topologyKey: "kubernetes.io/hostname"
          - weight: 98
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: tailscale.com/parent-resource
                  operator: In
                  values:
                  - ts-k8s-pod-cidrs
              topologyKey: "kubernetes.io/hostname"
          - weight: 97
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: tailscale.com/parent-resource
                  operator: In
                  values:
                  - ts-k8s-exit-node
              topologyKey: "kubernetes.io/hostname"
          - weight: 80
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: tailscale.com/parent-resource
                  operator: In
                  values:
                  - ts-k8s-homelab
              topologyKey: "kubernetes.io/hostname"
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: tailscale.com/parent-resource
                  operator: In
                  values:
                  - ts-k8s-disneyplus
              topologyKey: "kubernetes.io/hostname"
          - weight: 2
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: tailscale.com/parent-resource
                  operator: In
                  values:
                  - ts-k8s-hulu
              topologyKey: "kubernetes.io/hostname"
          - weight: 3
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: tailscale.com/parent-resource
                  operator: In
                  values:
                  - ts-k8s-netflix
              topologyKey: "kubernetes.io/hostname"
          - weight: 4
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: tailscale.com/parent-resource
                  operator: In
                  values:
                  - ts-k8s-app-home-cidrs
              topologyKey: "kubernetes.io/hostname"
---
apiVersion: tailscale.com/v1alpha1
kind: ProxyGroup
metadata:
  name: ts-proxygroup
spec:
  type: egress
  replicas: 2
  hostnamePrefix: ts-proxygroup
  proxyClass: ts-proxyclass
