---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tailscale-credentials
  namespace: network-system
spec:
  refreshInterval: "1m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: tailscale-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        client_id: "{{ .oauthClientId }}"
        client_secret: "{{ .oauthClientSecret }}"
  data:
    - secretKey: "oauthClientId"
      remoteRef:
        # metadataPolicy: Fetch
        key: "tailscale-client-credentials"
        property: "client-id"
    - secretKey: "oauthClientSecret"
      remoteRef:
        # metadataPolicy: Fetch
        key: "tailscale-client-credentials"
        property: "client-secret"
