apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: network-system
spec:
  driftDetection:
    mode: enabled
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://pkgs.tailscale.com/helmcharts
      chart: tailscale-operator
      version: 1.90.8
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    installCRDs: false
    oauthSecretVolume:
      secret:
        secretName: tailscale-credentials
