---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etherpad-plugins
  namespace: default
  annotations:
    nfs.io/storage-path: "containers/kubernetes/etherpad/plugins"
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: "nfs-dynamic"
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etherpad-var
  namespace: default
  annotations:
    nfs.io/storage-path: "containers/kubernetes/etherpad/var"
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: "nfs-dynamic"
  resources:
    requests:
      storage: 10Gi
