apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: etherpad-config
  namespace: default
spec:
  refreshInterval: "15s"
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: etherpad-config
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ADMIN_PASSWORD: "{{ .adminPassword }}"
  data:
  - secretKey: "adminPassword"
    remoteRef:
      # metadataPolicy: Fetch
      key: "etherpadConfig"
      property: "adminPassword"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: etherpad-database
  namespace: default
spec:
  refreshInterval: "15s"
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: etherpad-database
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DB_HOST: "{{ .databaseHost }}"
        DB_PORT: "{{ .databasePort }}"
        DB_NAME: "{{ .databaseName }}"
        DB_USER: "{{ .databaseUser }}"
        DB_PASS: "{{ .databasePass }}"
        DB_TYPE: "{{ .databaseType }}"
  data:
  - secretKey: "databaseHost"
    remoteRef:
      # metadataPolicy: Fetch
      key: "etherpadDatabase"
      property: "databaseHost"
  - secretKey: "databasePort"
    remoteRef:
      # metadataPolicy: Fetch
      key: "etherpadDatabase"
      property: "databasePort"
  - secretKey: "databaseName"
    remoteRef:
      # metadataPolicy: Fetch
      key: "etherpadDatabase"
      property: "databaseName"
  - secretKey: "databaseUser"
    remoteRef:
      # metadataPolicy: Fetch
      key: "etherpadDatabase"
      property: "databaseUser"
  - secretKey: "databasePass"
    remoteRef:
      # metadataPolicy: Fetch
      key: "etherpadDatabase"
      property: "databasePass"
  - secretKey: "databaseType"
    remoteRef:
      # metadataPolicy: Fetch
      key: "etherpadDatabase"
      property: "databaseType"
---
