apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault
  namespace: kube-system
spec:
  provider:
    vault:
      server: "http://vault.vault-internal:8200"
      path: "cubbyhole"
      version: "v2"
      auth:
        # caProvider:
        #   type: "Secret"
        #   namespace: "kube-system"
        #   name: ""
        #   key: ""
        tokenSecretRef:
          name: "vault-token"
          namespace: "kube-system"
          key: "token"
        # points to a secret that contains a vault token
        # https://www.vaultproject.io/docs/auth/token
        # kubernetes:
        #   mountPath: "kubernetes"
        #   # role: "app"
        #   secretRef:
        #     name: "vault-token"
        #     key: "token"
