---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager-system
  labels:
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
  annotations:
    metallb.universe.tf/address-pool: system
