---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tautulli-config
  namespace: tautulli
  annotations:
    nfs.io/storage-path: "containers/kubernetes/tautulli/config"
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: "nfs-dynamic"
  resources:
    requests:
      storage: 100Mi
