---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tautulli-tailscale
spec:
  defaultBackend:
    service:
      name: tautulli
      port:
        number: 8181
  ingressClassName: tailscale
  tls:
  - hosts:
    - tautulli
