apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tautulli
  namespace: default
spec:
  driftDetection:
    mode: enabled
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s-labs.github.io/helm-charts
      chart: app-template
      version: 4.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        defaultContainerOptions:
          resources:
            requests:
              cpu: 10m
              memory: 250Mi
            limits:
              memory: 2Gi
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            fsGroup: 3001
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups: [ 568, 911, 1000, 1001 ]
          tolerations:
          - key: "arm"
            operator: "Exists"
        containers:
          main:
            image:
              # renovate: repository=ghcr.io/tautulli/tautulli
              repository: ghcr.io/tautulli/tautulli
              tag: v2.16.0
            securityContext:
              runAsUser: 1000
              runAsGroup: 3001
            env:
              TZ: America/New_York
              PUID: 1000
              PGID: 3001
    service:
      main:
        # annotations:
        # traefik.ingress.kubernetes.io/service.nativelb: "true"
        controller: main
        ports:
          http:
            port: 8181
    ingress:
      main:
        annotations:
          kubernetes.io/ingress.class: traefik
          traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
          traefik.ingress.kubernetes.io/router.middlewares: "network-system-authentik@kubernetescrd"
        className: 'traefik'
        hosts:
        - host: &host "tautulli.homelab.heyser.xyz"
          paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: http
        tls:
        - hosts:
          - *host
          secretName: tautulli-homelab-heyser-xyz-tls
    persistence:
      config:
        existingClaim: tautulli-config
        advancedMounts:
          main:
            main:
            - path: "/config"
