apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: linkwarden-config
  namespace: default
spec:
  refreshInterval: "15s"
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: linkwarden-config
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        nextAuthSecret: "{{ .nextAuthSecret }}"
        meiliMasterKey: "{{ .meiliMasterKey }}"
  data:
  - secretKey: "nextAuthSecret"
    remoteRef:
      # metadataPolicy: Fetch
      key: "linkwardenConfig"
      property: "nextAuthSecret"
  - secretKey: "meiliMasterKey"
    remoteRef:
      # metadataPolicy: Fetch
      key: "linkwardenConfig"
      property: "meiliMasterKey"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: linkwarden-database
  namespace: default
spec:
  refreshInterval: "15s"
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: linkwarden-database
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        databasePassword: "{{ .databasePassword }}"
        databaseURL: "{{ .databaseURL }}"
  data:
  - secretKey: "databasePassword"
    remoteRef:
      # metadataPolicy: Fetch
      key: "linkwardenDatabase"
      property: "databasePassword"
  - secretKey: "databaseURL"
    remoteRef:
      # metadataPolicy: Fetch
      key: "linkwardenDatabase"
      property: "databaseURL"
---
