---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-subdir-external-provisioner
  namespace: storage-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
      chart: nfs-subdir-external-provisioner
      version: 4.0.18
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner-charts
        namespace: flux-system
      interval: 5m
  values:
    replicaCount: 3
    strategyType: RollingUpdate
    nfs:
      # server: 10.0.0.8
      # path: /kracko
      server: "10.0.0.10"
      path: "/kracko"  
      mountOptions:
        - "vers=4"
        - "minorversion=1"
        - "local_lock=posix"
        - "proto=tcp"
        - "noresvport"
        - "ac"
    storageClass:
      defaultClass: true
      name: "nfs-dynamic"
      pathPattern: "${.PVC.annotations.nfs.io/storage-path}"
      accessModes: ReadWriteMany
      archiveOnDelete: false
      provisionerName: k8s-sigs.io/nfs-subdir-external-provisioner
      reclaimPolicy: Retain
    podAnnotations:
      app.kubernetes.io/component: nfs
    tolerations:
    - effect: PreferNoSchedule
      key: node-role.kubernetes.io
      value: master
    - key: node-role.kubernetes.io/control-plane
      operator: Equal
      effect: NoSchedule
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - nfs-subdir-external-provisioner
            topologyKey: "kubernetes.io/hostname"
