apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: coder
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      # renovate: repository=codercom/code-server
      repository: codercom/code-server
      tag: 4.92.2

    env:
      TZ: "America/New_York"

    service:
      main:
        ports:
          http:
            port: &port 8080

    ingress:
      main:
        enabled: true
        ingressClassName: 'traefik'
        hosts:
        - host: code.homelab.heyser.xyz
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "code.homelab.heyser.xyz"
        - secretName: "code-homelab-heyser-xyz-tls"

    extraVolumeMounts:
      - name: development
        existingClaim: coder-development
        mountPath: /data
      - name: sshkey
        existingClaim: coder-sshkey
        mountPath: /home/coder/.ssh

    persistence:
      enabled: true
      storageClass: "nfs-dynamic"
      existingClaim: coder-config
      mountPath: /config

    podSecurityContext:
      runAsUser: 1001
      runAsGroup: 1001
      fsGroup: 1001
      fsGroupChangePolicy: OnRootMismatch

    resources:
      requests:
        memory: 100Mi
        cpu: 50m
      limits:
        memory: 500Mi

    tolerations:
    - key: "arm"
      operator: "Exists"
