---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: coder-config
  namespace: default
  annotations:
    nfs.io/storage-path: "containers/kubernetes/code-server"
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: "nfs-dynamic"
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: coder-sshkey
  namespace: default
  annotations:
    nfs.io/storage-path: "containers/kubernetes/code-ssh-key"
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: "nfs-dynamic"
  resources:
    requests:
      storage: 10Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: coder-development
  namespace: default
  annotations:
    nfs.io/storage-path: "development"
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: "nfs-dynamic"
  resources:
    requests:
      storage: 4Ti
