---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: coder-tailscale
spec:
  defaultBackend:
    service:
      name: coder
      port:
        number: 8080
  ingressClassName: tailscale
  tls:
    - hosts:
        - code
