apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault-unseal
  namespace: vault-system
spec:
  driftDetection:
    mode: enabled
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s-labs.github.io/helm-charts
      chart: app-template
      version: 4.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        type: cronjob
        defaultContainerOptions:
          resources:
            requests:
              cpu: 10m
              memory: 250Mi
            limits:
              memory: 2Gi
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            fsGroup: 3001
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups: [568,911,1000,1001]
          tolerations:
            - key: "arm"
              operator: "Exists"
        cronjob:
          schedule: "*/15 * * * *"
          failedJobsHistory: 1
          successfulJobsHistory: 1
          ttlSecondsAfterFinished: 3600
        containers:
          vault0:
            image:
               # renovate: repository=ghcr.io/omegion/vault-unseal
              repository: ghcr.io/omegion/vault-unseal
              tag: v0.25.1
            securityContext:
              runAsUser: 1000
              runAsGroup: 3001
            env:
              TZ: America/New_York
              PUID: 1000
              PGID: 3001
            envFrom:
              - secretRef:
                  name: vault-unseal
                  optional: false
            args: 
              - unseal
              - --address=http://vault-0.vault-internal:8200
              - --shard=${shard0}
              - --shard=${shard1}
          vault1:
            image:
               # renovate: repository=ghcr.io/omegion/vault-unseal
              repository: ghcr.io/omegion/vault-unseal
              tag: v0.25.1
            securityContext:
              runAsUser: 1000
              runAsGroup: 3001
            env:
              TZ: America/New_York
              PUID: 1000
              PGID: 3001
            envFrom:
              - secretRef:
                  name: vault-unseal
                  optional: false
            args: 
              - unseal
              - --address=http://vault-1.vault-internal:8200
              - --shard=${shard0}
              - --shard=${shard1}
          vault2:
            image:
               # renovate: repository=ghcr.io/omegion/vault-unseal
              repository: ghcr.io/omegion/vault-unseal
              tag: v0.25.1
            securityContext:
              runAsUser: 1000
              runAsGroup: 3001
            env:
              TZ: America/New_York
              PUID: 1000
              PGID: 3001
            envFrom:
              - secretRef:
                  name: vault-unseal
                  optional: false
            args: 
              - unseal
              - --address=http://vault-2.vault-internal:8200
              - --shard=${shard0}
              - --shard=${shard1}
          # vault3:
          #   image:
          #      # renovate: repository=ghcr.io/omegion/vault-unseal
          #     repository: ghcr.io/omegion/vault-unseal
          #     tag: v0.25.1
          #   securityContext:
          #     runAsUser: 1000
          #     runAsGroup: 3001
          #   env:
          #     TZ: America/New_York
          #     PUID: 1000
          #     PGID: 3001
          #   envFrom:
          #     - secretRef:
          #         name: vault-unseal
          #         optional: false
          #   args: 
          #     - unseal
          #     - --address=http://vault-3.vault-internal:8200
          #     - --shard=${shard0}
          #     - --shard=${shard1}
          # vault4:
          #   image:
          #      # renovate: repository=ghcr.io/omegion/vault-unseal
          #     repository: ghcr.io/omegion/vault-unseal
          #     tag: v0.25.1
          #   securityContext:
          #     runAsUser: 1000
          #     runAsGroup: 3001
          #   env:
          #     TZ: America/New_York
          #     PUID: 1000
          #     PGID: 3001
          #   envFrom:
          #     - secretRef:
          #         name: vault-unseal
          #         optional: false
          #   args: 
          #     - unseal
          #     - --address=http://vault-4.vault-internal:8200
          #     - --shard=${shard0}
          #     - --shard=${shard1}
    persistence:
      vault-0-config:
        existingClaim: vault-0-config
        advancedMounts:
          main:
            vault0:
              - path: "/.vault-unseal"
                readOnly: false
      vault-1-config:
        existingClaim: vault-1-config
        advancedMounts:
          main:
            vault1:
              - path: "/.vault-unseal"
                readOnly: false
      vault-2-config:
        existingClaim: vault-2-config
        advancedMounts:
          main:
            vault2:
              - path: "/.vault-unseal"
                readOnly: false
      vault-3-config:
        existingClaim: vault-3-config
        advancedMounts:
          main:
            vault3:
              - path: "/.vault-unseal"
                readOnly: false
      vault-4-config:
        existingClaim: vault-4-config
        advancedMounts:
          main:
            vault4:
              - path: "/.vault-unseal"
                readOnly: false
