apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: calibre
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        defaultContainerOptions:
          resources:
            requests:
              cpu: 10m
              memory: 250Mi
            limits:
              memory: 2Gi
        pod:
          securityContext:
            fsGroup: 1000
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups: [0,568,911,1001]
        containers:
          main:
            image:
              repository: linuxserver/calibre
              tag: 7.25.0
            securityContext:
              runAsUser: 0
              runAsGroup: 0
              allowPrivilegeEscalation: true
              privileged: true
            env:
              TZ: America/New_York
              PUID: "1000"
              PGID: "1000"
              GUID: "1000"
              UMASK_SET: "022"
              DISABLE_IPV6: "true"
              START_DOCKER: "false"
            envFrom:
              - secretRef:
                  name: calibre-credentials
                  optional: false
    service:
      main:
        annotations:
          traefik.ingress.kubernetes.io/service.nativelb: "true"
        controller: main
        ports:
          http:
            port: 8080
      webserver:
        controller: main
        type: LoadBalancer
        externalIPs:
        - 10.0.101.2
        annotations:
          metallb.universe.tf/allow-shared-ip: "calibre-share"
          metallb.universe.tf/address-pool: "default"
          metallb.universe.tf/loadBalancerIPs: 10.0.101.2
          cni.projectcalico.org/ipAddrs: '["10.0.101.2"]'
          traefik.ingress.kubernetes.io/service.nativelb: "true"
        externalTrafficPolicy: Local
        ports:
          webserver:
            port: 8081
      connect:
        controller: main
        type: LoadBalancer
        externalIPs:
        - 10.0.101.2
        annotations:
          metallb.universe.tf/allow-shared-ip: "calibre-share"
          metallb.universe.tf/address-pool: "default"
          metallb.universe.tf/loadBalancerIPs: 10.0.101.2
          cni.projectcalico.org/ipAddrs: '["10.0.101.2"]'
          traefik.ingress.kubernetes.io/service.nativelb: "true"
        ports:
          connect:
            enabled: true
            port: 9090
            protocol: TCP
            targetPort: 9090
    ingress:
      main:
        className: "traefik"
        # ingressClassName: nginx
        annotations:
          kubernetes.io/ingress.class: traefik
          traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
          traefik.ingress.kubernetes.io/router.middlewares: "network-system-authentik@kubernetescrd"
        hosts:
        - host: &host "calibre.homelab.heyser.xyz"
          paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: http
        tls:
        - hosts:
          - *host
          secretName: calibre-homelab-heyser-xyz-tls
      webserver:
        className: traefik
        # ingressClassName: nginx
        annotations:
          kubernetes.io/ingress.class: traefik
          traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
          traefik.ingress.kubernetes.io/router.middlewares: "network-system-authentik@kubernetescrd"
        hosts:
        - host: &webhost "calibre-web.homelab.heyser.xyz"
          paths:
          - path: /
            pathType: Prefix
            service:
              identifier: webserver
              port: webserver
        tls:
        - hosts:
          - *webhost
          secretName: calibre-homelab-heyser-xyz-tls
      connect:
        className: traefik
        # ingressClassName: nginx
        annotations:
          kubernetes.io/ingress.class: traefik
          traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
          # traefik.ingress.kubernetes.io/router.middlewares: "network-system-authentik@kubernetescrd"
        hosts:
        - host: &connecthost "calibre-connect.homelab.heyser.xyz"
          paths:
          - path: /
            pathType: Prefix
            service:
              identifier: connect
              port: connect
        tls:
        - hosts:
          - *connecthost
          secretName: calibre-homelab-heyser-xyz-tls

    # Note: If downloading very large torrents it might be worth using NFS for your download directory.
    # Beware if you are downloading torrents directly to a ZFS dataset that dataset will accrue fragmentation.
    persistence:
      config:
        existingClaim: calibre-config
        advancedMounts:
          main:
            main:
              - path: "/config"
                readOnly: false
      library:
        existingClaim: calibre-library
        advancedMounts:
          main:
            main:
              - path: "/config/Calibre Library"
