apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: calibre
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        defaultContainerOptions:
          resources:
            requests:
              cpu: 10m
              memory: 250Mi
            limits:
              memory: 2Gi
        pod:
          securityContext:
            fsGroup: 1001
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups: [568,911]
        containers:
          main:
            image:
              # renovate: repository=linuxserver/calibre
              repository: linuxserver/calibre
              tag: 7.18.0
            securityContext:
              runAsUser: 1001
              runAsGroup: 1001
            env:
              TZ: America/New_York
              PUID: "1001"
              PGID: "1001"
              UMASK_SET: "022"
            envFrom:
              - secretRef:
                  name: calibre-credentials
                  optional: false
    service:
      main:
        controller: main
        annotations:
          metallb.universe.tf/allow-shared-ip: "calibre-share"
          metallb.universe.tf/address-pool: "default"
        ports:
          http:
            port: 80
      webserver:
        controller: main
        type: LoadBalancer
        loadBalancerIP: 10.0.101.4
        annotations:
          metallb.universe.tf/allow-shared-ip: "calibre-share"
          metallb.universe.tf/address-pool: "default"
        externalTrafficPolicy: Local
        ports:
          webserver:
            port: 8081
      connect:
        controller: main
        type: LoadBalancer
        loadBalancerIP: 10.0.101.4
        annotations:
          metallb.universe.tf/allow-shared-ip: "calibre-share"
          metallb.universe.tf/address-pool: "default"
        ports:
          connect:
            enabled: true
            port: 9090
            protocol: TCP
            targetPort: 9090
    ingress:
      main:
        className: "traefik"
        # ingressClassName: nginx
        # annotations:
        #   nginx.ingress.kubernetes.io/auth-url: "https://auth.homelab.heyser.xyz/oauth2/auth"
        #   nginx.ingress.kubernetes.io/auth-signin: https://auth.homelab.heyser.xyz/oauth2/start
        hosts:
        - host: &host "calibre.homelab.heyser.xyz"
          paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: http
        tls:
        - hosts:
          - *host
          secretName: calibre-homelab-heyser-xyz-tls
      webserver:
        className: traefik
        # ingressClassName: nginx
        # annotations:
        #   nginx.ingress.kubernetes.io/auth-url: "https://auth.homelab.heyser.xyz/oauth2/auth"
        #   nginx.ingress.kubernetes.io/auth-signin: https://auth.homelab.heyser.xyz/oauth2/start
        hosts:
        - host: &webhost "calibre-web.homelab.heyser.xyz"
          paths:
          - path: /
            pathType: Prefix
            service:
              identifier: webserver
              port: http
        tls:
        - hosts:
          - *webhost
          secretName: calibre-web-homelab-heyser-xyz-tls

    # Note: If downloading very large torrents it might be worth using NFS for your download directory.
    # Beware if you are downloading torrents directly to a ZFS dataset that dataset will accrue fragmentation.
    persistence:
      config:
        existingClaim: calibre-config-config
        advancedMounts:
          main:
            main:
              - path: "/config"
      library:
        existingClaim: calibre-library-claim
        advancedMounts:
          main:
            main:
              - path: "/calibre-library"