apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: calibre
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      # renovate: repository=linuxserver/calibre
      repository: linuxserver/calibre
      tag: 7.18.0
    env:
      TZ: America/New_York
      PUID: "1001"
      PGID: "1001"
      GUAC_USER:
      - secretRef:
          name: calibre-secret
          key: calibre-user
      GUAC_PASS:
      - secretRef:
          name: calibre-secret
          key: calibre-pass
      UMASK_SET: "022"
    service:
      main:
        annotations:
          metallb.universe.tf/allow-shared-ip: "calibre-share"
          metallb.universe.tf/address-pool: "default"
        ports:
          http:
            port: 80
      webserver:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: 10.0.101.4
        annotations:
          metallb.universe.tf/allow-shared-ip: "calibre-share"
          metallb.universe.tf/address-pool: "default"
        externalTrafficPolicy: Local
      connect:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: 10.0.101.4
        annotations:
          metallb.universe.tf/allow-shared-ip: "calibre-share"
          metallb.universe.tf/address-pool: "default"
        ports:
          connect:
            enabled: true
            port: 9090
            protocol: TCP
            targetPort: 9090
    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        # ingressClassName: nginx
        # annotations:
        #   nginx.ingress.kubernetes.io/auth-url: "https://auth.homelab.heyser.xyz/oauth2/auth"
        #   nginx.ingress.kubernetes.io/auth-signin: https://auth.homelab.heyser.xyz/oauth2/start
        hosts:
        - host: calibre.homelab.heyser.xyz
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - calibre.homelab.heyser.xyz
        - secretName: calibre-homelab-heyser-xyz-tls
      webserver:
        enabled: true
        ingressClassName: traefik
        # ingressClassName: nginx
        # annotations:
        #   nginx.ingress.kubernetes.io/auth-url: "https://auth.homelab.heyser.xyz/oauth2/auth"
        #   nginx.ingress.kubernetes.io/auth-signin: https://auth.homelab.heyser.xyz/oauth2/start
        hosts:
        - host: calibre-web.homelab.heyser.xyz
          paths:
          - path: /
            pathType: Prefix
          service:
            name: "calibre-webserver"
            port: 8081
        tls:
        - hosts:
          - calibre-web.homelab.heyser.xyz
        - secretName: calibre-web-homelab-heyser-xyz-tls
      
    podSecurityContext:
      runAsUser: 1001
      runAsGroup: 1001
      fsGroup: 1001
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups: [568]
    # Note: If downloading very large torrents it might be worth using NFS for your download directory.
    # Beware if you are downloading torrents directly to a ZFS dataset that dataset will accrue fragmentation.
    persistence:
      config:
        enabled: true
        existingClaim: calibre-config-config
        mountPath: "/config"
      library:
        enabled: true
        existingClaim: calibre-library-claim
        mountPath: "/calibre-library"
    resources:
      requests:
        cpu: 10m
        memory: 250Mi
      limits:
        memory: 2Gi
    tolerations:
    - key: "arm"
      operator: "Exists"
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - nodeSelectorTerms:
          - matchExpressions:
              key: "kubernetes.io/arch"
              operator: "In"
              values:
              - "amd64"
