---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-config
  annotations:
    nfs.io/storage-path: "containers/kubernetes/calibre"
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: "nfs-dynamic"
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-library
  annotations:
    nfs.io/storage-path: "books"
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: "nfs-dynamic"
  resources:
    requests:
      storage: 100Gi
