apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: calibre-credentials
  namespace: default
spec:
  refreshInterval: "15s"
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: calibre-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        GUAC_USER: "{{ .calibreUser }}"
        GUAC_PASS: "{{ .calibrePassword }}"
        # CUSTOM_USER: "{{ .calibreUser }}"
        # PASSWORD: "{{ .calibrePassword }}"
  data:
    - secretKey: "calibreUser"
      remoteRef:
        # metadataPolicy: Fetch
        key: "calibreCredentials"
        property: "calibreUser"
    - secretKey: "calibrePassword"
      remoteRef:
        # metadataPolicy: Fetch
        key: "calibreCredentials"
        property: "calibrePassword"
