apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: calibre-credentials
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: calibre-credentials
    creationPolicy: Owner
    # template:
    #   type: Opaque
    #   data:
    #     GUAC_USER: "{{ guac-user | base64encode }}"
    #     GUAC_PASS: "{{ guac-pass | base64encode }}"
  dataFrom:
    - key: "secret/calibre-credentials"
  # data:
  #   - secretKey: "guac-user"
  #     remoteRef:
  #       key: "secret/calibre-credentials"
  #       property: "guac-user"
  #   - secretKey: "guac-pass"
  #     remoteRef:
  #       key: "secret/calibre-credentials"
  #       property: "guac-pass"
