apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: calibre-credentials
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: calibre-credentials
    creationPolicy: Owner
    # template:
    #   engineVersion: v2
    #   data:
    #     GUAC_USER: "{{ .creds.guac-user }}"
    #     GUAC_PASS: "{{ .creds.guac-pass }}"
  data:
    - secretKey: "creds"
      remoteRef:
        key: "secret/calibre-credentials"
        property: "creds.creds"
    # - secretKey: "guac-pass"
    #   remoteRef:
    #     key: "secret/calibre-credentials"
    #     property: "guac-pass"
