apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: calibre-credentials
spec:
  refreshInterval: "15s"
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: calibre-credentials
    creationPolicy: Owner
    # template:
    #   engineVersion: v2
    #   data:
    #     GUAC_USER: "{{ .GUAC_USER }}"
    #     GUAC_PASS: "{{ .GUAC_PASS }}"
  data:
    - secretKey: "GUAC_USER"
      remoteRef:
        metadataPolicy: Fetch
        key: "calibre-user"
        property: "calibre-user"
    - secretKey: "GUAC_PASS"
      remoteRef:
        metadataPolicy: Fetch
        key: "calibre-password"
        property: "calibre-password"
