apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: calibre-credentials
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: calibre-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        GUAC_USER: "{{ .guac-user }}"
        GUAC_PASS: "{{ .guac-pass }}"
  data:
    - secretKey: "guac-user"
      remoteRef:
        metadataPolicy: Fetch
        key: "calibre-credentials"
        property: "guac-user"
    - secretKey: "guac-pass"
      remoteRef:
        metadataPolicy: Fetch
        key: "calibre-credentials"
        property: "guac-pass"
