apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: calibre-user
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: calibre-user
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: GUAC_USER
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: calibre-pass
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: calibre-pass
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: GUAC_PASS
---
