apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-api-key
  namespace: cert-manager
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: cloudflare-api-key
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: cloudflare
