---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: truenas-homelab-heyser-xyz
spec:
  subject:
    organizations:
    - Heyser
  secretName: truenas-homelab-heyser-xyz-tls
  dnsNames:
    - storage.homelab.heyser.xyz
    - awoofy.homelab.heyser.xyz
    - kracko.homelab.heyser.xyz
  issuerRef:
    name: letsencrypt-prod
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: plex-homelab-heyser-xyz
spec:
  subject:
    organizations:
    - Heyser
  secretName: plex-homelab-heyser-xyz-tls
  dnsNames:
  - plex.homelab.heyser.xyz
  - plex.heyser.xyz
  issuerRef:
    name: letsencrypt-prod
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer
    group: cert-manager.io
---