---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: plex-ip
  labels:
    kubernetes.io/service-name: plex-ip
endpoints:
  - addresses:
      - 10.0.1.1
    conditions:
      ready: true
      serving: true
ports:
  - port: 32400
