---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: truenas-storage-tailscale
spec:
  defaultBackend:
    service:
      name: truenas-storage-ip
      port:
        number: 443
  ingressClassName: tailscale
  tls:
    - hosts:
        - storage
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: truenas-awoofy-tailscale
spec:
  defaultBackend:
    service:
      name: truenas-awoofy-ip
      port:
        number: 443
  ingressClassName: tailscale
  tls:
    - hosts:
        - awoofy
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: truenas-kracko-tailscale
spec:
  defaultBackend:
    service:
      name: truenas-kracko-ip
      port:
        number: 443
  ingressClassName: tailscale
  tls:
    - hosts:
        - kracko
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plex-tailscale
spec:
  defaultBackend:
    service:
      name: plex-ip
      port:
        number: 32400
  ingressClassName: tailscale
  tls:
    - hosts:
        - plex
---
