---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uptime-kuma-tailscale
spec:
  defaultBackend:
    service:
      name: uptime-kuma
      port:
        number: 3001
  ingressClassName: tailscale
  tls:
    - hosts:
        - uptime-kuma
