---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: intel-gpu-exporter
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts/
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        type: "daemonset"
        defaultContainerOptions:
          resources:
            requests:
              gpu.intel.com/i915: 1
              cpu: 100m
              memory: 100Mi
            limits:
              gpu.intel.com/i915: 1
              memory: 500Mi
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            privileged: true
          tolerations:
            - key: "arm"
              operator: "Exists"
          nodeSelector:
            intel.feature.node.kubernetes.io/gpu: "true"
        containers:
          main:
            image:
              # renovate: repository=ghcr.io/onedr0p/qbittorrent
              repository: ghcr.io/onedr0p/intel-gpu-exporter
              tag: rolling@sha256:1511f71b317fa7b7ef297bd2fb27f403800562b3461fc414992c245ee68335e2
            env:
              TZ: America/New_York
    service:
      main:
        controller: main
        ports:
          http:
            port: 8080
    serviceMonitor:
      main:
        enabled: false
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 10s
            relabelings:
              - sourceLabels: [__meta_kubernetes_pod_node_name]
                targetLabel: node
