apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plugin-barman-cloud
  namespace: storage-system
spec:
  driftDetection:
    mode: enabled
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://cloudnative-pg.github.io/charts
      chart: plugin-barman-cloud
      version: 0.5.0
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    replicaCount: 1
    containerSecurityContext:
      runAsUser: 26
      runAsGroup: 26
    # updateStrategy:
    # WARNING: the RollingUpdate strategy is not supported by the operator yet so it can
    # currently only use the Recreate strategy.
    # type: RollingUpdate
    # rollingUpdate:
    #   maxSurge: 1
    #   maxUnavailable: 1
