apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grimmory-data
  namespace: default
  annotations:
    nfs.io/storage-path: "containers/kubernetes/grimmory/data"
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: "nfs-dynamic"
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grimmory-mariadb-config
  namespace: default
  annotations:
    nfs.io/storage-path: "containers/kubernetes/grimmory/mariadb-config"
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: "nfs-dynamic"
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grimmory-books
  annotations:
    nfs.io/storage-path: "books"
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: "nfs-dynamic"
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grimmory-bookdrop
  annotations:
    nfs.io/storage-path: "books/grimmory/bookdrop"
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: "nfs-dynamic"
  resources:
    requests:
      storage: 100Gi
