apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grimmory-config
spec:
  refreshInterval: "1m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: grimmory-config
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DATABASE_USERNAME: "{{ .grimmoryDatabaseUsername }}"
        DATABASE_PASSWORD: "{{ .grimmoryDatabasePassword }}"
        DATABASE_URL: "{{ .grimmoryDatabaseURL }}"
  data:
    - secretKey: "grimmoryDatabaseURL"
      remoteRef:
        # metadataPolicy: Fetch
        key: "grimmory-config"
        property: "database-database-url"
    - secretKey: "grimmoryDatabaseUsername"
      remoteRef:
        # metadataPolicy: Fetch
        key: "grimmory-config"
        property: "grimmory-database-username"
    - secretKey: "grimmoryDatabasePassword"
      remoteRef:
        # metadataPolicy: Fetch
        key: "grimmory-config"
        property: "grimmory-database-password"
