apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grimmory-database-config
spec:
  refreshInterval: "1m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: grimmory-database-config
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        MARIADB_ROOT_PASSWORD: "{{ .grimmoryDatabaseRootPassword }}"
        MARIADB_DATABASE: "{{ .grimmoryDatabaseName }}"
        MARIADB_USER: "{{ .grimmoryDatabaseUsername }}"
        MARIADB_PASSWORD: "{{ .grimmoryDatabasePassword }}"
  data:
    - secretKey: "grimmoryDatabaseUsername"
      remoteRef:
        # metadataPolicy: Fetch
        key: "grimmory-database-config"
        property: "grimmory-database-username"
    - secretKey: "grimmoryDatabasePassword"
      remoteRef:
        # metadataPolicy: Fetch
        key: "grimmory-database-config"
        property: "grimmory-database-password"
    - secretKey: "grimmoryDatabaseRootPassword"
      remoteRef:
        # metadataPolicy: Fetch
        key: "grimmory-database-config"
        property: "grimmory-database-root-password"
    - secretKey: "grimmoryDatabaseName"
      remoteRef:
        # metadataPolicy: Fetch
        key: "grimmory-database-config"
        property: "grimmory-database-name"
