---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reloader
  namespace: kube-system
spec:
  driftDetection:
    mode: enabled
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://stakater.github.io/stakater-charts
      chart: reloader
      version: 2.2.6
      sourceRef:
        kind: HelmRepository
        name: stakater-charts
        namespace: flux-system
      interval: 5m
  values:
    reloader:
      enableHA: true
      podDisruptionBudget:
        enabled: true
        minAvailable: 1
      deployment:
        replicas: 3
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - reloader-reloader
                topologyKey: "kubernetes.io/hostname"
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Equal
        effect: NoSchedule
      - effect: PreferNoSchedule
        key: node-role.kubernetes.io
        value: master
