apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-api-key
  namespace: cert-manager-system
spec:
  refreshInterval: "1m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: cloudflare-api-key
    creationPolicy: Owner
  data:
    - secretKey: "api-key"
      remoteRef:
        key: "cloudflare-api-key"
        property: "api-key"

