apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: network-system
resources:
# renovate: depName=kubernetes-sigs/gateway-api
# - https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.5.1/experimental-install.yaml
- ./certificates.yaml
- ./traefik-crds.yaml
- ./traefik.yaml
