apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: coredns
  namespace: network-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.rancher.io
      chart: rke2-coredns
      version: 1.29.006
      sourceRef:
        kind: HelmRepository
        name: coredns-charts
        namespace: flux-system
      interval: 5m
  values:
    # nodelocal:
    #   enabled: true
    service:
      clusterIP: 10.254.0.10
      externalTrafficPolicy: Local
      annotations:
        metallb.universe.tf/allow-shared-ip: coredns
    rbac:
      create: true
    prometheus:
      service:
        enabled: false
        annotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "9153"
      monitor:
        enabled: false
    autoscaler:
      enabled: true
      min: 2
      max: 5
    servers:
    - zones:
      - zone: .
      port: 53
      plugins:
      - name: errors
      # Serves a /health endpoint on :8080, required for livenessProbe
      - name: health
        configBlock: |-
          lameduck 5s
      # Serves a /ready endpoint on :8181, required for readinessProbe
      - name: ready
      # Required to query kubernetes API for data
      - name: kubernetes
        parameters: cluster.local in-addr.arpa ip6.arpa homelab.heyser.lan homelab.heyser.xyz
        configBlock: |-
          pods insecure
          fallthrough in-addr.arpa ip6.arpa homelab.heyser.lan homelab.heyser.xyz
          ttl 30
      - name: prometheus
        parameters: 0.0.0.0:9153
      - name: forward
        parameters: . 10.0.100.3 10.0.0.1
        configBlock: |-
          except "cluster.local" "svc.cluster.local" ".svc"
          policy sequential
      - name: cache
        parameters: 30
      - name: loop
      - name: reload
      - name: loadbalance
    zoneFiles:
    - filename: heyser.xyz
      domain: heyser.xyz
      contents: |
        heyser.xyz.   IN SOA  kyrie.ns.cloudflare.com. dns.cloudflare.com. 2325026458 10000 2400 604800 1800
        heyser.xyz. IN A   10.0.100.1
        homelab.heyser.xyz. IN A   10.0.100.1
        *.homelab.heyser.xyz. IN A   10.0.100.1
