apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.jetstack.io/
      chart: cert-manager
      version: v1.16.3
      sourceRef:
        kind: HelmRepository
        name: jetstack-charts
        namespace: flux-system
      interval: 5m
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    crds: 
      enabled: true
      keep: true
    replicaCount: 3
    strategy:
      type: RollingUpdate
      maxSurge: 1
      maxUnavailable: 1
    podDisruptionBudget:
      enabled: true
      minAvailable: 1
    webhook:
      replicaCount: 3
      strategy:
        type: RollingUpdate
        maxSurge: 1
        maxUnavailable: 1
      podDisruptionBudget:
        enabled: true
        minAvailable: 1
    #   enabled: true
    #   tolerations:
    #   - key: "arm"
    #     operator: "Exists"
    # extraArgs:
    # - --dns01-recursive-nameservers=1.1.1.1:53
    # - --dns01-recursive-nameservers-only
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                  - cert-manager
              topologyKey: "kubernetes.io/hostname"
    tolerations:
    - key: "arm"
      operator: "Exists"
    cainjector:
      replicaCount: 3
      # extraArgs:
      #   - --leader-elect=false
      tolerations:
      - key: "arm"
        operator: "Exists"
      strategy:
        type: RollingUpdate
        maxSurge: 1
        maxUnavailable: 1
      podDisruptionBudget:
        enabled: true
        minAvailable: 1
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - cert-manager
                topologyKey: "kubernetes.io/hostname"
      
    # prometheus:
    #   enabled: true
    #   servicemonitor:
    #     enabled: true
    #     prometheusInstance: monitoring
