apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shelfmark-config
  namespace: default
  annotations:
    nfs.io/storage-path: "containers/kubernetes/shelfmark/config"
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: "nfs-dynamic"
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shelfmark-books
  annotations:
    nfs.io/storage-path: "books"
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: "nfs-dynamic"
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shelfmark-audiobooks
  annotations:
    nfs.io/storage-path: "media/Audiobooks"
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: "nfs-dynamic"
  resources:
    requests:
      storage: 1Ti
---
