apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: shelfmark
  namespace: default
spec:
  driftDetection:
    mode: enabled
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s-labs.github.io/helm-charts
      chart: app-template
      version: 4.6.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        defaultContainerOptions:
          resources:
            requests:
              cpu: 10m
              memory: 250Mi
            limits:
              memory: 2Gi
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            fsGroup: 0
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups: [ 568, 911, 1000, 1001, 3001 ]
          tolerations:
          - key: "arm"
            operator: "Exists"
        containers:
          main:
            image:
              # renovate: repository=ghcr.io/calibrain/shelfmark
              repository: ghcr.io/calibrain/shelfmark
              tag: v1.0.4
            securityContext:
              runAsUser: 0
              runAsGroup: 0
              allowPrivilegeEscalation: true
              capabilities:
                add: [ "CAP_SETGID", "CAP_SETUID" ]
            env:
              TZ: America/New_York
              SWAGGER_ENABLED: "false"
              PUID: "1000"
              PGID: "3001"

    service:
      main:
        controller: main
        type: ClusterIP
        ports:
          http:
            port: 8084
            targetPort: 8084
    ingress:
      main:
        className: 'traefik'
        annotations:
          kubernetes.io/ingress.class: traefik
          traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
          # traefik.ingress.kubernetes.io/router.middlewares: "network-system-authentik@kubernetescrd"
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Downloaders
          gethomepage.dev/icon: shelfmark.png
          gethomepage.dev/name: Shelfmark
          gethomepage.dev/description: Shelfmark is a self-hosted book management application that allows users to organize and manage their digital book collections.
        hosts:
        - host: &host "shelfmark.homelab.heyser.xyz"
          paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: http
        tls:
        - hosts:
          - *host
          secretName: shelfmark-homelab-heyser-xyz-tls

    persistence:
      shelfmark-config:
        existingClaim: shelfmark-config
        advancedMounts:
          main:
            main:
            - path: "/config"
              readOnly: false
      shelfmark-books:
        existingClaim: shelfmark-books
        advancedMounts:
          main:
            main:
            - path: "/books"
              readOnly: false
      shelfmark-audiobooks:
        existingClaim: shelfmark-audiobooks
        advancedMounts:
          main:
            main:
            - path: "/audiobooks"
              readOnly: false
