apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: kube-system
spec:
  driftDetection:
    mode: enabled
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://charts.external-secrets.io
      chart: external-secrets
      version: 0.19.2
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
      interval: 5m
  maxHistory: 3
  install:
    replace: true
    crds: CreateReplace
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    force: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  rollback:
    recreate: true
    force: true
    cleanupOnFail: true
  values:
    global:
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          effect: NoSchedule
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - external-secrets
              topologyKey: "kubernetes.io/hostname"
    installCRDs: true
    replicaCount: 3
    leaderElect: true
    serviceMonitor:
      enabled: false
    webhook:
      replicaCount: 3
      port: 443
      podDisruptionBudget:
        enabled: true
        minAvailable: 1
      serviceMonitor:
        enabled: false
    certController:
      serviceMonitor:
        enabled: false
    metrics:
      service:
        enabled: false
    podDisruptionBudget:
      enabled: true
      minAvailable: 1