apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 10m
  path: "./kube-system/external-secrets/chart"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  healthChecks:
  - apiVersion: helm.toolkit.fluxcd.io/v2beta1
    kind: HelmRelease
    name: external-secrets
    namespace: kube-system
  retryInterval: 1m
  timeout: 3m
