apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-ddns-star-root
  namespace: network-system
spec:
  refreshInterval: "15s"
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: cloudflare-ddns-star-root
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ZONE_ID: "{{ .cloudflareZoneID }}"
        RECORD_ID: "{{ .cloudflareRecordID }}"
        AUTH_KEY: "{{ .cloudflareAuthKey }}"
        NAME: "*.heyser.xyz"
        AUTH_EMAIL: "rumblpak@gmail.com"
        PROXIED: "false"
  data:
    - secretKey: "cloudflareZoneID"
      remoteRef:
        # metadataPolicy: Fetch
        key: "cloudflare-zone-id"
        property: "zone-id"
    - secretKey: "cloudflareRecordID"
      remoteRef:
        # metadataPolicy: Fetch
        key: "cloudflare-record-id"
        property: "wildcard-heyser-xyz"
    - secretKey: "cloudflareAuthKey"
      remoteRef:
        # metadataPolicy: Fetch
        key: "cloudflare-auth-key"
        property: "auth-key"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-ddns-root
  namespace: network-system
spec:
  refreshInterval: "15s"
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: cloudflare-ddns-root
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ZONE_ID: "{{ .cloudflareZoneID }}"
        RECORD_ID: "{{ .cloudflareRecordID }}"
        AUTH_KEY: "{{ .cloudflareAuthKey }}"
        NAME: "heyser.xyz"
        AUTH_EMAIL: "rumblpak@gmail.com"
        PROXIED: "false"
  data:
    - secretKey: "cloudflareZoneID"
      remoteRef:
        # metadataPolicy: Fetch
        key: "cloudflare-zone-id"
        property: "zone-id"
    - secretKey: "cloudflareRecordID"
      remoteRef:
        # metadataPolicy: Fetch
        key: "cloudflare-record-id"
        property: "heyser-xyz"
    - secretKey: "cloudflareAuthKey"
      remoteRef:
        # metadataPolicy: Fetch
        key: "cloudflare-auth-key"
        property: "auth-key"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-ddns-star-homelab
  namespace: network-system
spec:
  refreshInterval: "15s"
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: cloudflare-ddns-star-homelab
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ZONE_ID: "{{ .cloudflareZoneID }}"
        RECORD_ID: "{{ .cloudflareRecordID }}"
        AUTH_KEY: "{{ .cloudflareAuthKey }}"
        NAME: "*.homelab.heyser.xyz"
        AUTH_EMAIL: "rumblpak@gmail.com"
        PROXIED: "false"
  data:
    - secretKey: "cloudflareZoneID"
      remoteRef:
        # metadataPolicy: Fetch
        key: "cloudflare-zone-id"
        property: "zone-id"
    - secretKey: "cloudflareRecordID"
      remoteRef:
        # metadataPolicy: Fetch
        key: "cloudflare-record-id"
        property: "wildcard-homelab-heyser-xyz"
    - secretKey: "cloudflareAuthKey"
      remoteRef:
        # metadataPolicy: Fetch
        key: "cloudflare-auth-key"
        property: "auth-key"
