---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: youtubedl-config
  namespace: youtubedl
  annotations:
    nfs.io/storage-path: "containers/kubernetes/youtubedl-material/config"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "nfs-dynamic"
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: youtubedl-audio
  namespace: youtubedl
  annotations:
    nfs.io/storage-path: "media/youtube/audio"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "nfs-dynamic"
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: youtubedl-subscriptions
  namespace: youtubedl
  annotations:
    nfs.io/storage-path: "media/youtube/subscriptions"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "nfs-dynamic"
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: youtubedl-users
  namespace: youtubedl
  annotations:
    nfs.io/storage-path: "containers/kubernetes/youtubedl-material/users"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "nfs-dynamic"
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: youtubedl-video
  namespace: youtubedl
  annotations:
    nfs.io/storage-path: "media/youtube/video"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "nfs-dynamic"
  resources:
    requests:
      storage: 100Gi
---