apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: audiobookshelf
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      # renovate: repository=tzahi12345/youtubedl-material
      repository: tzahi12345/youtubedl-material
      tag: 4.3.2

    env:
      TZ: "America/New_York"

    ingress:
      main:
        enabled: true
        ingressClassName: 'traefik'
        hosts:
        - host: youtubedl.homelab.heyser.xyz
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "youtubedl.homelab.heyser.xyz"

    persistence:
      config:
        enabled: true
        existingClaim: youtubedl-config
      audio:
        enabled: true
        existingClaim: youtubedl-audio
      subscriptions:
        enabled: true
        existingClaim: youtubedl-subscriptions
      users:
        enabled: true
        existingClaim: youtubedl-users
      video:
        enabled: true
        existingClaim: youtubedl-video

    resources:
      requests:
        memory: 100Mi
        cpu: 50m
      limits:
        memory: 500Mi

    tolerations:
    - key: "arm"
      operator: "Exists"
