apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: youtubedl
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        defaultContainerOptions:
          resources:
            requests:
              cpu: 10m
              memory: 250Mi
            limits:
              memory: 2Gi
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            fsGroup: 1001
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups: [568,911]
          tolerations:
            - key: "arm"
              operator: "Exists"
        containers:
          main:
            image:
              # renovate: repository=tzahi12345/youtubedl-material
              repository: tzahi12345/youtubedl-material
              tag: nightly-2024-09-17
            securityContext:
              runAsUser: 1001
              runAsGroup: 1001
            env:
              TZ: America/New_York
    ingress:
      main:
        className: 'traefik'
        hosts:
        - host: &host "youtubedl.homelab.heyser.xyz"
          paths:
          - path: /
            pathType: Prefix
            service:
              indentifier: main
              port: http
        tls:
        - hosts:
          - *host
          secretName: youtubedl-homelab-heyser-xyz-tls
    persistence:
      config:
        existingClaim: youtubedl-config
      audio:
        existingClaim: youtubedl-audio
      subscriptions:
        existingClaim: youtubedl-subscriptions
      users:
        existingClaim: youtubedl-users
      video:
        existingClaim: youtubedl-video
