apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: youtubedl
  namespace: default
spec:
  driftDetection:
    mode: enabled
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        defaultContainerOptions:
          resources:
            requests:
              cpu: 10m
              memory: 250Mi
            limits:
              memory: 2Gi
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            fsGroup: 3001
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups: [568,911,1000,1001]
          tolerations:
            - key: "arm"
              operator: "Exists"
        containers:
          main:
            image:
              # renovate: repository=tzahi12345/youtubedl-material
              repository: tzahi12345/youtubedl-material
              tag: nightly-2025-03-18
            securityContext:
              runAsUser: 0
              runAsGroup: 0
            env:
              TZ: America/New_York
              UID: 1000
              GID: 3001
    service:
      main:
        # annotations:
          # traefik.ingress.kubernetes.io/service.nativelb: "true"
        controller: main
        ports:
          http:
            port: 17442
    ingress:
      main:
        annotations:
          kubernetes.io/ingress.class: traefik
          traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
          traefik.ingress.kubernetes.io/router.middlewares: "network-system-authentik@kubernetescrd"
        className: 'traefik'
        hosts:
        - host: &host "youtubedl.homelab.heyser.xyz"
          paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: http
        tls:
        - hosts:
          - *host
          secretName: youtubedl-homelab-heyser-xyz-tls
    persistence:
      config:
        existingClaim: youtubedl-config
        advancedMounts:
          main:
            main:
              - path: "/app/appdata"
      audio:
        existingClaim: youtubedl-audio
        advancedMounts:
          main:
            main:
              - path: "/app/audio"
      subscriptions:
        existingClaim: youtubedl-subscriptions
        advancedMounts:
          main:
            main:
              - path: "/app/subscriptions"
      users:
        existingClaim: youtubedl-users
        advancedMounts:
          main:
            main:
              - path: "/app/users"
      video:
        existingClaim: youtubedl-video
        advancedMounts:
          main:
            main:
              - path: "/app/video"
