apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: navidrome
  namespace: default
spec:
  driftDetection:
    mode: enabled
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        defaultContainerOptions:
          resources:
            requests:
              cpu: 10m
              memory: 250Mi
            limits:
              memory: 2Gi
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            fsGroup: 3001
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups: [568,911,1000,1001]
          tolerations:
            - key: "arm"
              operator: "Exists"
        containers:
          main:
            image:
              # renovate: repository=docker.io/deluan/navidrome
              repository: docker.io/deluan/navidrome
              tag: 0.55.2@sha256:3a66e262b7ea836faa06c08ad5b32076c49e9e63e2fa4de10080c8e9be9f0846
            securityContext:
              runAsUser: 1000
              runAsGroup: 3001
            env:
              TZ: America/New_York
              ND_DATAFOLDER: /data
              ND_MUSICFOLDER: /music
              ND_SCANNER_SCHEDULE: "@every 1h"
              ND_LOGLEVEL: info
              ND_SESSIONTIMEOUT: 24h
              ND_ENABLETRANSCODINGCONFIG: true
              ND_ENABLEINSIGHTSCOLLECTOR: false
    service:
      main:
        # annotations:
          # traefik.ingress.kubernetes.io/service.nativelb: "true"
        controller: main
        type: ClusterIP
        ports:
          http:
            port: 4533
            targetPort: 4533
    ingress:
      main:
        className: "traefik"
        # ingressClassName: nginx
        annotations:
        #   nginx.ingress.kubernetes.io/auth-url: "https://auth.homelab.heyser.xyz/oauth2/auth"
        #   nginx.ingress.kubernetes.io/auth-signin: https://auth.homelab.heyser.xyz/oauth2/start
          kubernetes.io/ingress.class: traefik
          traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
          # traefik.ingress.kubernetes.io/router.middlewares: "network-system-authentik@kubernetescrd"
        hosts:
        - host: &host "navidrome.homelab.heyser.xyz"
          paths:
          - path: /
            pathType: Prefix
            service: 
              identifier: main
              port: http
        - host: &mhost "music.homelab.heyser.xyz"
          paths:
          - path: /
            pathType: Prefix
            service: 
              identifier: main
              port: http
        tls:
        - hosts:
          - *host
          - *mhost
          secretName: navidrome-homelab-heyser-xyz-tls
    persistence:
      data:
        existingClaim: navidrome-data
        advancedMounts:
          main:
            main:
              - path: "/data"
                readOnly: false
      music:
        existingClaim: navidrome-music
        advancedMounts:
          main:
            main:
              - path: "/music"
                readOnly: false
      cache:
        emptyDir: {}
