apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: navidrome-data
  annotations:
    nfs.io/storage-path: "containers/kubernetes/navidrome"
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: "nfs-dynamic"
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: navidrome-music
  annotations:
    nfs.io/storage-path: "media/music"
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: "nfs-dynamic"
  resources:
    requests:
      storage: 4Ti
