apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: navidrome-tailscale
spec:
  defaultBackend:
    service:
      name: navidrome-main
      port:
        number: 4533
  ingressClassName: tailscale
  tls:
    - hosts:
        - navidrome
