apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: immich-database-backup
spec:
  schedule: "0 0 2 * * *" # Daily at 2am
  immediate: true
  cluster:
    name: immich-database
  backupOwnerReference: self
