apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: minio
spec:
  configuration:
    destinationPath: "s3://immich/"
    endpointURL: "http://10.0.0.8:30292"
    s3Credentials:
      accessKeyId:
        name: immich-minio-credentials
        key: minio-user
      secretAccessKey:
        name: immich-minio-credentials
        key: minio-password
    tags:
      backupRetentionPolicy: "expire"
    historyTags:
      backupRetentionPolicy: "keep"
    # wal:
    #   compression: zstd
  retentionPolicy: "7d"
  instanceSidecarConfiguration:
    logLevel: debug
    retentionPolicyIntervalSeconds: 3600