apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
spec:
  driftDetection:
    mode: enabled
  interval: 10m
  chart:
    spec:
      # renovate: registryUrl=https://ghcr.io/immich-app/immich-charts
      chart: immich
      version: 0.10.0
      sourceRef:
        kind: HelmRepository
        name: immich
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      main:
        containers:
          main:
            image:
              # renovate: repository=ghcr.io/immich-app/immich-server
              repository: ghcr.io/immich-app/immich-server
              tag: v2.0.1
            env:
              TZ: America/New_York
    immich:
      persistence:
        library:
          existingClaim: immich-library

    server:
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: traefik
          traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
          traefik.ingress.kubernetes.io/router.middlewares: "network-system-authentik@kubernetescrd"
        hosts:
        - host: &host immich.homelab.heyser.xyz
          paths:
          - path: /
            service:
              identifier: main
        tls:
        - hosts:
          - *host
          secretName: immich-homelab-heyser-xyz-tls

    valkey:
      enabled: true
      controllers:
        main:
          containers:
            main:
              image:
                # renovate: repository=ghcr.io/valkey/valkey
                repository: ghcr.io/valkey/valkey
                tag: 8.1.4-alpine@sha256:e706d1213aaba6896c162bb6a3a9e1894e1a435f28f8f856d14fab2e10aa098b
                pullPolicy: IfNotPresent

    machine-learning:
      enabled: true
      resources:
        requests:
          cpu: 500m
          memory: 1Gi
        limits:
          cpu: 1
          memory: 2Gi
      containers:
        main:
          image:
            # renovate: repository=ghcr.io/immich-app/immich-machine-learning
            repository: ghcr.io/immich-app/immich-machine-learning
            tag: v2.0.1
          env:
            TZ: America/New_York
            TRANSFORMERS_CACHE: /cache
      persistence:
        cache:
          enabled: true
          type: persistentVolumeClaim
          existingClaim: immich-machine-learning
