apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
spec:
  driftDetection:
    mode: enabled
  interval: 10m
  chart:
    spec:
      # renovate: registryUrl=https://ghcr.io/immich-app/immich-charts
      chart: immich
      version: 0.10.1
      sourceRef:
        kind: HelmRepository
        name: immich
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        defaultContainerOptions:
          resources:
            requests:
              memory: 2Gi
              gpu.intel.com/i915: 1
            limits:
              memory: 4Gi
              gpu.intel.com/i915: 1
        pod:
          securityContext:
            fsGroup: 3001
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups: [ 0, 568, 911, 1000, 1001 ]
        containers:
          main:
            image:
              # renovate: repository=ghcr.io/immich-app/immich-server
              repository: ghcr.io/immich-app/immich-server
              tag: v2.2.3
            env:
              TZ: America/New_York
              IMMICH_LOG_LEVEL: "debug"
              IMMICH_MACHINE_LEARNING_URL: "http://immich-machine-learning:3000"
              NO_COLOR: "true"
              UPLOAD_LOCATION: "/library"
              REDIS_HOSTNAME: "immich-valkey"
              DB_STORAGE_TYPE: "HDD"
              DB_HOSTNAME:
                valueFrom:
                  secretKeyRef:
                    name: immich-database-app
                    key: host
                    optional: false
              DB_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: immich-database-app
                    key: pgpass
                    optional: false
              DB_USERNAME:
                valueFrom:
                  secretKeyRef:
                    name: immich-database-app
                    key: user
                    optional: false
              DB_URL:
                valueFrom:
                  secretKeyRef:
                    name: immich-database-app
                    key: fqdn-uri
                    optional: false
              DB_PORT:
                valueFrom:
                  secretKeyRef:
                    name: immich-database-app
                    key: port
                    optional: false
              DB_DATABASE_NAME:
                valueFrom:
                  secretKeyRef:
                    name: immich-database-app
                    key: dbname
                    optional: false

    immich:
      persistence:
        library:
          existingClaim: immich-library

    server:
      controllers:
        main:
          replicas: 2
          strategy: RollingUpdate
          rollingUpdate:
            unavailable: 1
            surge: 1
          defaultContainerOptions:
            resources:
              requests:
                memory: 2Gi
                gpu.intel.com/i915: 1
              limits:
                memory: 4Gi
                gpu.intel.com/i915: 1
          pod:
            securityContext:
              fsGroup: 3001
              fsGroupChangePolicy: "OnRootMismatch"
              supplementalGroups: [ 0, 568, 911, 1000, 1001 ]
          containers:
            main:
              image:
                # renovate: repository=ghcr.io/immich-app/immich-server
                repository: ghcr.io/immich-app/immich-server
                tag: v2.2.3
      ingress:
        main:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: traefik
            traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
            # traefik.ingress.kubernetes.io/router.middlewares: "network-system-authentik@kubernetescrd"
          hosts:
          - host: &host immich.homelab.heyser.xyz
            paths:
            - path: /
              service:
                identifier: main
          tls:
          - hosts:
            - *host
            secretName: immich-homelab-heyser-xyz-tls

    valkey:
      enabled: true
      controllers:
        main:
          containers:
            main:
              image:
                # renovate: repository=valkey/valkey
                repository: valkey/valkey
                tag: 9.0.0-alpine
                pullPolicy: IfNotPresent

    machine-learning:
      enabled: true
      controllers:
        main:
          replicas: 3
          strategy: RollingUpdate
          rollingUpdate:
            unavailable: 1
            surge: 1
          defaultContainerOptions:
            resources:
              requests:
                memory: 2Gi
              limits:
                memory: 4Gi
          pod:
            securityContext:
              fsGroup: 3001
              fsGroupChangePolicy: "OnRootMismatch"
              supplementalGroups: [ 0, 568, 911, 1000, 1001 ]
          containers:
            main:
              image:
                # renovate: repository=ghcr.io/immich-app/immich-machine-learning
                repository: ghcr.io/immich-app/immich-machine-learning
                tag: v2.2.2
              env:
                TZ: America/New_York
                TRANSFORMERS_CACHE: /cache
      persistence:
        cache:
          enabled: true
          type: persistentVolumeClaim
          existingClaim: immich-machine-learning
