apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
spec:
  driftDetection:
    mode: enabled
  interval: 10m
  chart:
    spec:
      # renovate: registryUrl=https://ghcr.io/immich-app/immich-charts
      chart: immich
      version: 0.10.0
      sourceRef:
        kind: HelmRepository
        name: immich
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        containers:
          main:
            image:
              # renovate: repository=ghcr.io/immich-app/immich-server
              repository: ghcr.io/immich-app/immich-server
              tag: v2.1.0
            env:
              TZ: America/New_York
              IMMICH_LOG_LEVEL: "debug"
              IMMICH_MACHINE_LEARNING_URL: "http://immich-machine-learning:3000"
              NO_COLOR: "true"
              UPLOAD_LOCATION: "/library"
              REDIS_HOSTNAME: "immich-valkey"
              DB_STORAGE_TYPE: "HDD"
              DB_HOSTNAME:
                valueFrom:
                  secretKeyRef:
                    name: immich-database-app
                    key: host
                    optional: false
              DB_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: immich-database-app
                    key: pgpass
                    optional: false
              DB_USERNAME:
                valueFrom:
                  secretKeyRef:
                    name: immich-database-app
                    key: user
                    optional: false
              DB_URL:
                valueFrom:
                  secretKeyRef:
                    name: immich-database-app
                    key: fqdn-uri
                    optional: false
              DB_PORT:
                valueFrom:
                  secretKeyRef:
                    name: immich-database-app
                    key: port
                    optional: false
              DB_DATABASE_NAME:
                valueFrom:
                  secretKeyRef:
                    name: immich-database-app
                    key: dbname
                    optional: false

    immich:
      persistence:
        library:
          existingClaim: immich-library

    server:
      ingress:
        main:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: traefik
            traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
            # traefik.ingress.kubernetes.io/router.middlewares: "network-system-authentik@kubernetescrd"
          hosts:
          - host: &host immich.homelab.heyser.xyz
            paths:
            - path: /
              service:
                identifier: main
          tls:
          - hosts:
            - *host
            secretName: immich-homelab-heyser-xyz-tls

    valkey:
      enabled: true
      controllers:
        main:
          containers:
            main:
              image:
                # renovate: repository=docker.io/valkey/valkey
                repository: docker.io/valkey/valkey
                tag: 8.1.4-alpine
                pullPolicy: IfNotPresent

    machine-learning:
      enabled: true
      resources:
        requests:
          cpu: 500m
          memory: 1Gi
        limits:
          cpu: 1
          memory: 2Gi
      containers:
        main:
          image:
            # renovate: repository=ghcr.io/immich-app/immich-machine-learning
            repository: ghcr.io/immich-app/immich-machine-learning
            tag: v2.1.0
          env:
            TZ: America/New_York
            TRANSFORMERS_CACHE: /cache
      persistence:
        cache:
          enabled: true
          type: persistentVolumeClaim
          existingClaim: immich-machine-learning
