---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library
  annotations:
    nfs.io/storage-path: "containers/kubernetes/immich/library"
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: "nfs-dynamic"
  resources:
    requests:
      storage: 1Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-machine-learning
  annotations:
    nfs.io/storage-path: "containers/kubernetes/immich/machine-learning"
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: "nfs-dynamic"
  resources:
    requests:
      storage: 10Gi
