apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: booklore
  namespace: default
spec:
  driftDetection:
    mode: enabled
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s-labs.github.io/helm-charts
      chart: app-template
      version: 4.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        defaultContainerOptions:
          resources:
            requests:
              cpu: 10m
              memory: 250Mi
            limits:
              memory: 2Gi
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            fsGroup: 3001
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups: [ 568, 911, 1000, 1001 ]
            allowPrivilegeEscalation: true
          tolerations:
          - key: "arm"
            operator: "Exists"
        containers:
          main:
            image:
              # renovate: repository=booklore/booklore
              repository: booklore/booklore
              tag: v1.3.3
            securityContext:
              runAsUser: 1000
              runAsGroup: 3001
              allowPrivilegeEscalation: true
            env:
              TZ: America/New_York
              PUID: 1000
              PGID: 3001
              SWAGGER_ENABLED: "false"
              USER_ID: 0
              GROUP_ID: 0
            envFrom:
            - secretRef:
                name: booklore-config
                optional: false
      mariadb:
        defaultContainerOptions:
          resources:
            requests:
              cpu: 10m
              memory: 250Mi
            limits:
              memory: 2Gi
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            fsGroup: 3001
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups: [ 568, 911, 1000, 1001 ]
          tolerations:
          - key: "arm"
            operator: "Exists"
        containers:
          mariadb:
            image:
              # renovate: repository=mariadb
              repository: mariadb
              tag: 11.8.3
            env:
              TZ: America/New_York
              PUID: 1000
              PGID: 3001
            envFrom:
            - secretRef:
                name: booklore-database-config
                optional: false
    service:
      main:
        controller: main
        type: ClusterIP
        ports:
          http:
            port: 6060
            targetPort: 6060
      mariadb:
        controller: mariadb
        type: ClusterIP
        ports:
          mariadb:
            port: 3306
            targetPort: 3306
    ingress:
      main:
        className: 'traefik'
        annotations:
          kubernetes.io/ingress.class: traefik
          traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
          # traefik.ingress.kubernetes.io/router.middlewares: "network-system-authentik@kubernetescrd"
        hosts:
        - host: &host "booklore.homelab.heyser.xyz"
          paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: http
        tls:
        - hosts:
          - *host
          secretName: booklore-homelab-heyser-xyz-tls

    persistence:
      booklore-data:
        existingClaim: booklore-data
        advancedMounts:
          main:
            main:
            - path: "/app/data"
              readOnly: false
      booklore-books:
        existingClaim: booklore-books
        advancedMounts:
          main:
            main:
            - path: "/books"
              readOnly: false
      booklore-bookdrop:
        existingClaim: booklore-bookdrop
        advancedMounts:
          main:
            main:
            - path: "/bookdrop"
              readOnly: false
      mariadb-config:
        existingClaim: booklore-mariadb-config
        advancedMounts:
          mariadb:
            mariadb:
            - path: "/config"
              readOnly: false
