apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: booklore-data
  namespace: default
  annotations:
    nfs.io/storage-path: "containers/kubernetes/booklore/data"
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: "nfs-dynamic"
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: booklore-mariadb-config
  namespace: default
  annotations:
    nfs.io/storage-path: "containers/kubernetes/booklore/mariadb-config"
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: "nfs-dynamic"
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: booklore-books
  annotations:
    nfs.io/storage-path: "books"
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: "nfs-dynamic"
  resources:
    requests:
      storage: 100Gi
