apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: booklore-database-config
spec:
  refreshInterval: "1m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: booklore-database-config
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        MYSQL_ROOT_PASSWORD: "{{ .bookloreDatabaseRootPassword }}"
        MYSQL_DATABASE: "{{ .bookloreDatabaseName }}"
        MYSQL_USER: "{{ .bookloreDatabaseUsername }}"
        MYSQL_PASSWORD: "{{ .bookloreDatabasePassword }}"
  data:
    - secretKey: "bookloreDatabaseUsername"
      remoteRef:
        # metadataPolicy: Fetch
        key: "booklore-database-config"
        property: "booklore-database-username"
    - secretKey: "bookloreDatabasePassword"
      remoteRef:
        # metadataPolicy: Fetch
        key: "booklore-database-config"
        property: "booklore-database-password"
    - secretKey: "bookloreDatabaseRootPassword"
      remoteRef:
        # metadataPolicy: Fetch
        key: "booklore-database-config"
        property: "booklore-database-root-password"
    - secretKey: "bookloreDatabaseName"
      remoteRef:
        # metadataPolicy: Fetch
        key: "booklore-database-config"
        property: "booklore-database-name"
