---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: booklore-tailscale
spec:
  defaultBackend:
    service:
      name: booklore
      port:
        number: 6060
  ingressClassName: tailscale
  tls:
    - hosts:
        - booklore
