
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: adguard-home-config
  namespace: network-system
  labels:
    app.kubernetes.io/name: adguard-home
    app.kubernetes.io/instance: adguard
data:
  AdGuardHome.yaml: |
      bind_host: 0.0.0.0
      bind_port: 3000
      beta_bind_port: 0
      users: []
      auth_attempts: 5
      block_auth_min: 15
      http_proxy: ""
      language: en
      rlimit_nofile: 0
      debug_pprof: false
      web_session_ttl: 720
      dns:
        bind_hosts:
        - 0.0.0.0
        port: 53
        statistics_interval: 1
        querylog_enabled: false
        querylog_file_enabled: false
        querylog_interval: 30
        querylog_size_memory: 1000
        anonymize_client_ip: true
        protection_enabled: true
        blocking_mode: default
        blocking_ipv4: ""
        blocking_ipv6: ""
        blocked_response_ttl: 10
        parental_block_host: family-block.dns.adguard.com
        safebrowsing_block_host: standard-block.dns.adguard.com
        ratelimit: 0
        ratelimit_whitelist: []
        refuse_any: true
        upstream_dns:
        - 'tls://dns.quad9.net'
        - 'tls://dns11.quad9.net'
        upstream_dns_file: ""
        bootstrap_dns:
        - 9.9.9.11
        - 149.112.112.11
        - 2620:fe::11
        - 2620:fe::fe:11
        all_servers: true
        fastest_addr: false
        allowed_clients: []
        disallowed_clients: []
        blocked_hosts: []
        cache_size: 16777216
        cache_ttl_min: 0
        cache_ttl_max: 300
        bogus_nxdomain: []
        aaaa_disabled: false
        enable_dnssec: true
        edns_client_subnet: false
        max_goroutines: 300
        ipset: []
        filtering_enabled: true
        filters_update_interval: 12
        parental_enabled: false
        safesearch_enabled: false
        safebrowsing_enabled: false
        safebrowsing_cache_size: 1048576
        safesearch_cache_size: 1048576
        parental_cache_size: 1048576
        cache_time: 30
        rewrites: []
        blocked_services: []
        local_domain_name: heyser.lan
        resolve_clients: true
        local_ptr_upstreams:
        - 10.0.0.1
        - 10.0.0.11
        - 10.0.0.12
        - 10.0.0.13
        - 10.0.0.14
      tls:
        enabled: false
        server_name: ""
        force_https: false
        port_https: 443
        port_dns_over_tls: 853
        port_dns_over_quic: 784
        port_dnscrypt: 0
        dnscrypt_config_file: ""
        allow_unencrypted_doh: false
        strict_sni_check: false
        certificate_chain: ""
        private_key: ""
        certificate_path: ""
        private_key_path: ""
      filters:
      - enabled: true
        url: https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
        name: AdGuard DNS filter
        id: 1
      - enabled: true
        url: https://github.com/notracking/hosts-blocklists/raw/master/adblock/adblock.txt
        name: Awesome Hosts Blocklist
        id: 2
      - enabled: true
        url: https://blocklistproject.github.io/Lists/adguard/phishing-ags.txt
        name: BLP - phishing
        id: 3
      - enabled: true
        url: https://blocklistproject.github.io/Lists/adguard/scam-ags.txt
        name: BLP - scam
        id: 4
      - enabled: true
        url: https://blocklistproject.github.io/Lists/adguard/tracking-ags.txt
        name: BLP - tracking
        id: 5
      - enabled: true
        url: https://blocklistproject.github.io/Lists/adguard/abuse-ags.txt
        name: BLP - abuse
        id: 6
      whitelist_filters: []
      user_rules:
      - '@@||aa.paramountplus.com^'
      - '@@||cbsinteractive.hb.omtrdc.net^'
      - '@@||ads.play.cbsi.video^'
      - '@@||pubads.g.doubleclick.net^'
      - '@@||go.redirectingat.com^'
      - '@@||ping.ui.com^'
      - '@@||trace.svc.ui.com^'
      - '@@||albert.apple.com^'
      - '@@||captive.apple.com^'
      - '@@||gs.apple.com^'
      - '@@||humb.apple.com^'
      - '@@||static.ips.apple.com^'
      - '@@||sq-device.apple.com^'
      - '@@||tbsc.apple.com^'
      - '@@||time-ios.apple.com^'
      - '@@||time.apple.com^'
      - '@@||time-macos.apple.com^'
      - '@@||push.apple.com^'
      - '@@||deviceenrollment.apple.com^'
      - '@@||deviceservices-external.apple.com^'
      - '@@||gdmf.apple.com^'
      - '@@||identity.apple.com^'
      - '@@||iprofiles.apple.com^'
      - '@@||mdmenrollment.apple.com^'
      - '@@||setup.icloud.com^'
      - '@@||vpp.itunes.apple.com       ^'
      - '@@||appldnld.apple.com^'
      - '@@||configuration.apple.com^'
      - '@@||gdmf.apple.com^'
      - '@@||gg.apple.com^'
      - '@@||gnf-mdn.apple.com^'
      - '@@||gnf-mr.apple.com^'
      - '@@||gs.apple.com^'
      - '@@||ig.apple.com^'
      - '@@||mesu.apple.com^'
      - '@@||ns.itunes.apple.com^'
      - '@@||oscdn.apple.com^'
      - '@@||osrecovery.apple.com^'
      - '@@||skl.apple.com^'
      - '@@||swcdn.apple.com^'
      - '@@||swdist.apple.com^'
      - '@@||swdownload.apple.com^'
      - '@@||swscan.apple.com^'
      - '@@||updates-http.cdn-apple.com^'
      - '@@||updates.cdn-apple.com^'
      - '@@||xp.apple.com^'
      - '@@||itunes.apple.com^'
      - '@@||apps.apple.com^'
      - '@@||mzstatic.com^'
      - '@@||ppq.apple.com^'
      - '@@||appldnld.apple.com.edgesuite.net^'
      - '@@||itunes.com^'
      - '@@||lcdn-registration.apple.com^'
      - '@@||suconfig.apple.com^'
      - '@@||xp-cdn.apple.com^'
      - '@@||lcdn-locator.apple.com^'
      - '@@||serverstatus.apple.com^'
      - '@@||appattest.apple.com^'
      - '@@||certs.apple.com^'
      - '@@||crl.apple.com^'
      - '@@||crl.entrust.net^'
      - '@@||crl3.digicert.com'
      - '@@||crl4.digicert.com^'
      - '@@||ocsp.apple.com^'
      - '@@||ocsp.digicert.cn^'
      - '@@||ocsp.digicert.com^'
      - '@@||ocsp.entrust.net^'
      - '@@||ocsp2.apple.com^'
      - '@@||valid.apple.com^'
      - '@@||appleid.apple.com^'
      - '@@||appleid.cdn-apple.com^'
      - '@@||idmsa.apple.com^'
      - '@@||gsa.apple.com^'
      - '@@||apple-cloudkit.com^'
      - '@@||apple-livephotoskit.com^'
      - '@@||apzones.com^'
      - '@@||cdn-apple.com^'
      - '@@||gc.apple.com^'
      - '@@||icloud.com^'
      - '@@||icloud.com.cn^'
      - '@@||icloud.apple.com^'
      - '@@||icloud-content.com^'
      - '@@||iwork.apple.com^'
      - '@@||mask.icloud.com^'
      - '@@||mask-h2.icloud.com^'
      - '@@||mask-api.icloud.com^'
      - '@@||audiocontentdownload.apple.com^'
      - '@@||devimages-cdn.apple.com^'
      - '@@||download.developer.apple.com^'
      - '@@||playgrounds-assets-cdn.apple.com^'
      - '@@||playgrounds-cdn.apple.com^'
      - '@@||sylvan.apple.com^'
      - '@@||bnc.lt^'
      - '@@||click.pstmrk.it^'
      - '@@||gleam.io^'
      - '@@||click.linksynergy.com^'
      - '@@||v.ringcentral.com^'
      - '@@||pixeldrain.com^'
      - '@@||emjcd.com^'
      dhcp:
        enabled: false
        interface_name: ""
        dhcpv4:
          gateway_ip: ""
          subnet_mask: ""
          range_start: ""
          range_end: ""
          lease_duration: 86400
          icmp_timeout_msec: 1000
          options: []
        dhcpv6:
          range_start: ""
          lease_duration: 86400
          ra_slaac_only: false
          ra_allow_slaac: false
      clients: []
      log_compress: false
      log_localtime: false
      log_max_backups: 0
      log_max_size: 100
      log_max_age: 3
      log_file: ""
      verbose: false
      schema_version: 10
---
apiVersion: v1
kind: Service
metadata:
  name: adguard-home-dns-tcp
  namespace: network-system
  labels:
    app.kubernetes.io/name: adguard-home
    app.kubernetes.io/instance: adguard
  annotations:
    cni.projectcalico.org/ipAddrs: '["10.0.100.2"]'
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  externalIPs:
    - 10.0.100.2
  ports:
  - port: 53
    targetPort: 53
    protocol: TCP
    name: dns-tcp
  selector:
    app.kubernetes.io/name: adguard-home
    app.kubernetes.io/instance: adguard
---
# Source: adguard-home/templates/common.yaml
apiVersion: v1
kind: Service
metadata:
  name: adguard-home-dns-udp
  namespace: network-system
  labels:
    app.kubernetes.io/instance: adguard
    app.kubernetes.io/name: adguard-home
  annotations:
    cni.projectcalico.org/ipAddrs: '["10.0.100.2"]'
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  externalIPs:
    - 10.0.100.2
  ports:
  - port: 53
    targetPort: 53
    protocol: UDP
    name: dns-udp
  selector:
    app.kubernetes.io/name: adguard-home
    app.kubernetes.io/instance: adguard
---
# Source: adguard-home/templates/common.yaml
apiVersion: v1
kind: Service
metadata:
  name: adguard-home
  namespace: network-system
  labels:
    app.kubernetes.io/instance: adguard
    app.kubernetes.io/name: adguard-home
  annotations:
    cni.projectcalico.org/ipAddrs: '["10.0.100.2"]'
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  externalIPs:
    - 10.0.100.2
  ports:
  - port: 3000
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: adguard-home
    app.kubernetes.io/instance: adguard
---
# Source: adguard-home/templates/common.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adguard-home
  namespace: network-system
  labels:
    app.kubernetes.io/instance: adguard
    app.kubernetes.io/name: adguard-home
spec:
  revisionHistoryLimit: 3
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: adguard-home
      app.kubernetes.io/instance: adguard
  template:
    metadata:
      labels:
        app.kubernetes.io/name: adguard-home
        app.kubernetes.io/instance: adguard
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - adguard-home
            topologyKey: "kubernetes.io/hostname"
      serviceAccountName: default
      automountServiceAccountToken: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      initContainers:
        - command:
          - sh
          - -c
          - |
            if [ ! -f /opt/adguardhome/conf/AdGuardHome.yaml ]; then
              mkdir -p /opt/adguardhome/conf
              cp /tmp/AdGuardHome.yaml /opt/adguardhome/conf/AdGuardHome.yaml
            fi
          image: busybox
          imagePullPolicy: IfNotPresent
          name: copy-configmap
          securityContext:
            runAsUser: 0
          volumeMounts:
          - mountPath: /tmp/AdGuardHome.yaml
            name: adguard-home-config
            subPath: AdGuardHome.yaml
          - mountPath: /opt/adguardhome/conf
            name: config
      containers:
      - name: adguard-home
        # renovate: repository=adguard/adguardhome
        image: "adguard/adguardhome:v0.107.55"
        imagePullPolicy: IfNotPresent
        args:
        - --config
        - /opt/adguardhome/conf/AdGuardHome.yaml
        - --work-dir
        - /opt/adguardhome/work
        - --no-check-update
        env:
        - name: TZ
          value: America/New York
        ports:
        - name: dns-tcp
          containerPort: 53
          protocol: TCP
        - name: dns-udp
          containerPort: 53
          protocol: UDP
        - name: http
          containerPort: 3000
          protocol: TCP
        volumeMounts:
        - name: adguard-home-config
          mountPath: /tmp/AdGuardHome.yaml
          subPath: AdGuardHome.yaml
        - name: config
          mountPath: /opt/adguardhome/conf
        resources:
          limits:
            cpu: "2"
            memory: "1Gi"
          requests:
            cpu: "250m"
            memory: "256Mi"
        livenessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 0
          failureThreshold: 3
          timeoutSeconds: 1
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 0
          failureThreshold: 3
          timeoutSeconds: 1
          periodSeconds: 10
        startupProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 0
          failureThreshold: 30
          timeoutSeconds: 1
          periodSeconds: 5
      volumes:
      - name: adguard-home-config
        configMap:
          name: adguard-home-config
      - name: config
        emptyDir:
          medium: Memory
      tolerations:
      - effect: PreferNoSchedule
        key: node-role.kubernetes.io
        value: master
      - key: node-role.kubernetes.io/control-plane
        operator: Equal
        effect: NoSchedule
---
# Source: adguard-home/templates/common.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: adguard-home
  namespace: network-system
  labels:
    app.kubernetes.io/instance: adguard
    app.kubernetes.io/name: adguard-home
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - "dns.homelab.heyser.xyz"
        - "adguard.homelab.heyser.xyz"
      secretName: "adguard-homelab-heyser-xyz-tls"
  rules:
    - host: "dns.homelab.heyser.xyz"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: adguard-home
                port:
                  number: 3000
    - host: "adguard.homelab.heyser.xyz"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: adguard-home
                port:
                  number: 3000
