apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: adguard-home-dns
  namespace: network-system
spec:
  gatewayClassName: traefik
  listeners:
  - name: adguard-home-https
    protocol: HTTPS
    port: 443
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        name: adguard-homelab-heyser-xyz-tls
        namespace: network-system
  - name: adguard-home-dns-http
    protocol: HTTP
    port: 80
    allowedRoutes:
      namespaces:
        from: All
  - name: adguard-home-dns-tcp
    protocol: TCP
    port: 53
    allowedRoutes:
      kinds:
      - kind: TCPRoute
      namespaces:
        from: All
  - name: adguard-home-dns-udp
    protocol: UDP
    port: 53
    allowedRoutes:
      kinds:
      - kind: UDPRoute
  - name: adguard-home-dns-tls-tcp
    protocol: TLS
    port: 853
    allowedRoutes:
      kinds:
      - kind: TCPRoute
      namespaces:
        from: All
    tls:
      mode: Passthrough
  - name: adguard-home-dns-quic-udp
    protocol: UDP
    port: 784
    allowedRoutes:
      kinds:
      - kind: UDPRoute
      namespaces:
        from: All
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: adguard-home-dns-http
  namespace: network-system
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: adguard-home-dns
  hostnames:
    - dns.homelab.heyser.xyz
  rules:
  - matches:
      - path:
          type: PathPrefix
          value: /dns-query
    backendRefs:
      - name: adguard-dns
        namespace: network-system
        port: 443
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: adguard-home-adguard-https
  namespace: network-system
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: adguard-home-dns
      sectionName: adguard-home-https
  hostnames:
    - adguard.homelab.heyser.xyz
  rules:
  - matches:
     - path:
         type: PathPrefix
         value: /
    backendRefs:
      - name: adguard-dns
        namespace: network-system
        port: 443
    filters:
      - type: ExtensionRef
        extensionRef:
          group: traefik.io
          kind: Middleware
          name: authentik
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: adguard-home-adguard-http
  namespace: network-system
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: adguard-home-dns
      sectionName: adguard-home-dns-http
  hostnames:
    - adguard.homelab.heyser.xyz
  rules:
  - matches:
      - path:
          type: PathPrefix
          value: /
    filters:
      - type: RequestRedirect
        requestRedirect:
          scheme: https
          statusCode: 301
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: adguard-home-dns-tcp
  namespace: network-system
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: adguard-home-dns
      sectionName: adguard-home-dns-tcp
  rules:
    - name: adguard-home-dns-tcp
      backendRefs:
      - name: adguard-home-dns-tcp
        namespace: network-system
        port: 53
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: UDPRoute
metadata:
  name: adguard-home-dns-udp
  namespace: network-system
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: adguard-home-dns
      sectionName: adguard-home-dns-udp
  rules:
    - name: adguard-home-dns-udp
      backendRefs:
      - name: adguard-home-dns-udp
        namespace: network-system
        port: 53
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: adguard-home-dns-tls-tcp
  namespace: network-system
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: adguard-home-dns
      sectionName: adguard-home-dns-tls-tcp
  rules:
    - name: adguard-home-dns-tls-tcp
      backendRefs:
      - name: adguard-home-dns-tls-tcp
        namespace: network-system
        port: 853
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: UDPRoute
metadata:
  name: adguard-home-dns-quic-udp
  namespace: network-system
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: adguard-home-dns
      sectionName: adguard-home-dns-quic-udp
  rules:
    - name: adguard-home-dns-quic-udp
      backendRefs:
      - name: adguard-home-dns-quic-udp
        namespace: network-system
        port: 784
