apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: adguard-home-dns
  namespace: network-system
spec:
  gatewayClassName: traefik-gateway
  listeners:
  - name: adguard-home-https
    protocol: HTTPS
    port: 443
    allowedRoutes:
      namespaces:
        from: All
  - name: adguard-home-dns-http
    protocol: HTTP
    port: 3000
    allowedRoutes:
      namespaces:
        from: All
  - name: adguard-home-dns-tcp
    protocol: TCP
    port: 53
    allowedRoutes:
      kinds:
      - kind: TCPRoute
  - name: adguard-home-dns-udp
    protocol: UDP
    port: 53
    allowedRoutes:
      kinds:
      - kind: UDPRoute
  - name: adguard-home-dns-tls-tcp
    protocol: TCP
    port: 853
    allowedRoutes:
      kinds:
      - kind: TCPRoute
  - name: adguard-home-dns-quic-udp
    protocol: UDP
    port: 784
    allowedRoutes:
      kinds:
      - kind: UDPRoute
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: adguard-home-dns-http
  namespace: network-system
spec:
  parentRefs:
  - name: adguard-home-http
    sectionName: http
    kind: Gateway
  hostnames:
    - dns.homelab.heyser.xyz
  rules:
  - matches:
      - path:
          type: PathPrefix
          value: /dns-query
    backendRefs:
      - name: adguard-home-https
        namespace: network-system
        port: 443
  - matches:
     - path:
         type: PathPrefix
         value: /
    backendRefs:
      - name: adguard-home-https
        namespace: network-system
        port: 443
    filters:
      - type: ExtensionRef
        extensionRef:
          group: traefik.io
          kind: Middleware
          name: network-system-authentik
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: adguard-home-adguard-http
  namespace: network-system
spec:
  parentRefs:
  - name: adguard-home-http
    sectionName: http
    kind: Gateway
  hostnames:
    - adguard.homelab.heyser.xyz
  rules:
  - matches:
      - path:
          type: PathPrefix
          value: /dns-query
    backendRefs:
      - name: adguard-home-https
        namespace: network-system
        port: 443
  - matches:
     - path:
         type: PathPrefix
         value: /
    backendRefs:
      - name: adguard-home-https
        namespace: network-system
        port: 443
    filters:
      - type: ExtensionRef
        extensionRef:
          group: traefik.io
          kind: Middleware
          name: network-system-authentik
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: adguard-home-dns-tcp
  namespace: network-system
spec:
  rules:
    - name: adguard-home-dns-tcp
      backendRefs:
      - name: adguard-home-dns-tcp
        namespace: network-system
        port: 53
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: UDPRoute
metadata:
  name: adguard-home-dns-udp
  namespace: network-system
spec:
  rules:
    - name: adguard-home-dns-udp
      backendRefs:
      - name: adguard-home-dns-udp
        namespace: network-system
        port: 53
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: adguard-home-dns-tls-tcp
  namespace: network-system
spec:
  rules:
    - name: adguard-home-dns-tls-tcp
      backendRefs:
      - name: adguard-home-dns-tls-tcp
        namespace: network-system
        port: 853
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: UDPRoute
metadata:
  name: adguard-home-dns-quic-udp
  namespace: network-system
spec:
  rules:
    - name: adguard-home-dns-quic-udp
      backendRefs:
      - name: adguard-home-dns-quic-udp
        namespace: network-system
        port: 784
