apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: network-system
resources:
- ./certificate.yaml
- ./configmap.yaml
- ./deployment.yaml
- ./service.yaml
- ./ingress.yaml
- ./tailscale.yaml
