---
apiVersion: v1
kind: Service
metadata:
  name: adguard-home-dns-tcp
  namespace: network-system
  labels:
    app.kubernetes.io/name: adguard-home
    app.kubernetes.io/instance: adguard
  annotations:
    cni.projectcalico.org/ipAddrs: '["10.0.100.2"]'
    traefik.ingress.kubernetes.io/service.nativelb: "true"
    metallb.universe.tf/loadBalancerIPs: 10.0.100.2
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  externalIPs:
    - 10.0.100.2
  ports:
  - port: 53
    targetPort: 53
    protocol: TCP
    name: dns-tcp
  selector:
    app.kubernetes.io/name: adguard-home
    app.kubernetes.io/instance: adguard
---
# Source: adguard-home/templates/common.yaml
apiVersion: v1
kind: Service
metadata:
  name: adguard-home-dns-udp
  namespace: network-system
  labels:
    app.kubernetes.io/instance: adguard
    app.kubernetes.io/name: adguard-home
  annotations:
    cni.projectcalico.org/ipAddrs: '["10.0.100.2"]'
    traefik.ingress.kubernetes.io/service.nativelb: "true"
    metallb.universe.tf/loadBalancerIPs: 10.0.100.2
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  externalIPs:
    - 10.0.100.2
  ports:
  - port: 53
    targetPort: 53
    protocol: UDP
    name: dns-udp
  selector:
    app.kubernetes.io/name: adguard-home
    app.kubernetes.io/instance: adguard
---
# Source: adguard-home/templates/common.yaml
apiVersion: v1
kind: Service
metadata:
  name: adguard-home
  namespace: network-system
  labels:
    app.kubernetes.io/instance: adguard
    app.kubernetes.io/name: adguard-home
  annotations:
    cni.projectcalico.org/ipAddrs: '["10.0.100.2"]'
    traefik.ingress.kubernetes.io/service.nativelb: "true"
    metallb.universe.tf/loadBalancerIPs: 10.0.100.2
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  externalIPs:
    - 10.0.100.2
  ports:
  - port: 3000
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: adguard-home
    app.kubernetes.io/instance: adguard
---
