---
apiVersion: traefik.io/v1alpha1
kind: TraefikService
metadata:
  name: adguard-dns
  namespace: network-system
spec:
  mirroring:
    name: adguard-dns
    port: 443
    mirrorBody: true
    maxBodySize: -1
    mirrors:
      - name: adguard-home-index-0
        port: 443
        percent: 100
      - name: adguard-home-index-1
        port: 443
        percent: 100
      - name: adguard-home-index-2
        port: 443
        percent: 100
      - name: adguard-home-index-3
        port: 443
        percent: 100
      - name: adguard-home-index-4
        port: 443
        percent: 100
      - name: adguard-home-index-5
        port: 443
        percent: 100
      - name: adguard-home-index-6
        port: 443
        percent: 100
      - name: adguard-home-index-7
        port: 443
        percent: 100
      - name: adguard-home-index-8
        port: 443
        percent: 100
      - name: adguard-home-index-9
        port: 443
        percent: 100
      - name: adguard-home-index-10
        port: 443
        percent: 100
      - name: adguard-home-index-11
        port: 443
        percent: 100
      - name: adguard-home-index-12
        port: 443
        percent: 100
      - name: adguard-home-index-13
        port: 443
        percent: 100
