apiVersion: admissionregistration.k8s.io/v1alpha1
kind: MutatingAdmissionPolicy
metadata:
  name: set-image-pull-policy-always
spec:
  reinvocationPolicy: Never
  matchConstraints:
    matchPolicy: Equivalent
    namespaces:
      matchLabels:
        # Target specific namespace
        kubernetes.io/metadata.name: "upgrade-system" 
    resourceRules:
    - apiGroups: [""]
      apiVersions: ["v1"]
      operations: ["CREATE", "UPDATE"]
      resources: ["pods"]
  mutations:
  - patchStrategicMerge:
      spec:
        containers:
        - name: "*"
          imagePullPolicy: Always
        initContainers:
        - name: "*"
          imagePullPolicy: Always
---
apiVersion: admissionregistration.k8s.io/v1alpha1
kind: MutatingAdmissionPolicyBinding
metadata:
  name: set-image-pull-policy-always-binding
spec:
  policyName: set-image-pull-policy-always
  matchResources:
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: "upgrade-system"
