apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: homepage
  namespace: default
  labels:
    app.kubernetes.io/name: homepage
  annotations:
    kubernetes.io/service-account.name: homepage
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage-pve-yaml
spec:
  refreshInterval: "1m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: homepage-pve-yaml
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        proxmox.yaml: |
          pve:
            url: https://10.0.0.9:8006
            token: root@pam!homepage
            secert: "{{ .pveToken }}"
  data:
  - secretKey: "pveToken"
    remoteRef:
      # metadataPolicy: Fetch
      key: "homepage-pve-token"
      property: "pve-token"
