apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: authentik
  namespace: network-system
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://charts.goauthentik.io
      chart: authentik
      version: 2024.12.2
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      affinity:
        podAntiAffinity: hard
    deploymentStrategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
    server:
      replicas: 3
      envFrom:
        - secretRef:
            name: authentik-secret-key
      pdb:
        enabled: true
        minAvailable: 1
      ingress:
        ingressClassName: traefik
        enabled: true
        hosts:
        - host: &host "auth.homelab.heyser.xyz"
          paths:
          - path: "/"
            pathType: Prefix
        tls:
        - *host
    worker:
      replicas: 3
      envFrom:
        - secretRef:
            name: authentik-secret-key
      pdb:
        enabled: true
        minAvailable: 1
    postgresql:
      enabled: true
      global:
        storageClass: nfs-dynamic
      auth:
        existingSecret: "authentik-credentials"
        secretKeys:
          adminPasswordKey: "adminPassword"
          userPasswordKey: "userPassword"
          replicationPasswordKey: "replicationPassword"
      primary:
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/component
                  operator: In
                  values:
                  - primary
              topologyKey: "kubernetes.io/hostname"
        persistence:
          enabled: true
          existingClaim: "authentik-postgresql-data-claim"
      readReplicas:
        replicaCount: 3
    redis:
      enabled: true
      auth:
        enabled: false
      master:
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/component
                  operator: In
                  values:
                  - master
              topologyKey: "kubernetes.io/hostname"

