apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: authentik
  namespace: network-system
spec:
  interval: 15m
  chart:
    spec:
      chart: authentik
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    replicas: 3
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
    worker:
      replicas: 3
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxSurge: 1
          maxUnavailable: 1
    ingress:
      ingressClassName: traefik
      enabled: true
      hosts:
      - host: auth.homelab.heyser.xyz
        paths:
        - path: "/"
          pathType: Prefix
    postgresql:
      enabled: true
      global:
        storageClass: nfs-dynamic
      primary:
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/component
                  operator: In
                  values:
                  - primary
              topologyKey: "kubernetes.io/hostname"
        persistence:
          enabled: true
          existingClaim: "authentik-postgresql-data-claim"
      readReplicas:
        replicaCount: 3
    redis:
      enabled: true
      global:
        storageClass: nfs-dynamic
      auth:
        enabled: true
      master:
        persistence:
          existingClaim: "authentik-redis-data-claim"
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/component
                  operator: In
                  values:
                  - master
              topologyKey: "kubernetes.io/hostname"
