apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-postgresql-data-claim
  namespace: network-system
  annotations:
    nfs.io/storage-path: "containers/kubernetes/authentik/postgresql"
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: "nfs-dynamic"
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-redis-data-claim
  namespace: network-system
  annotations:
    nfs.io/storage-path: "containers/kubernetes/authentik/redis"
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: "nfs-dynamic"
  resources:
    requests:
      storage: 10Gi
