apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-credentials
  namespace: network-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: authentik-credentials
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: authentik-credentials
