apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-credentials
  namespace: network-system
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: authentik-credentials
    creationPolicy: Owner
  data:
    - secretKey: "adminPassword"
      remoteRef:
        key: "secret/authentik-credentials"
        property: "adminPassword"
    - secretKey: "userPassword"
      remoteRef:
        key: "secret/authentik-credentials"
        property: "userPassword"
    - secretKey: "replicationPassword"
      remoteRef:
        key: "secret/authentik-credentials"
        property: "replicationPassword"
    