---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-feature-discovery
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes-sigs.github.io/node-feature-discovery/charts
      chart: node-feature-discovery
      version: 0.17.1
      sourceRef:
        kind: HelmRepository
        name: kubernetes-sigs-nfd-charts
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    tls:
      enable: true
      certManager: true
    worker:
      tolerations:
        - key: arm
          operator: Exists
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
        - effect: "NoExecute"
          operator: "Exists"
        - effect: "NoSchedule"
          operator: "Exists"
        - key: node-role.kubernetes.io/control-plane
          operator: Equal
          effect: NoSchedule
        - effect: PreferNoSchedule
          key: node-role.kubernetes.io
          value: master
    master:
      tolerations:
        - key: arm
          operator: Exists
