---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-feature-discovery
  namespace: kube-system
spec:
  driftDetection:
    mode: enabled
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes-sigs.github.io/node-feature-discovery/charts
      chart: node-feature-discovery
      version: 0.18.3
      sourceRef:
        kind: HelmRepository
        name: kubernetes-sigs-nfd-charts
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    tls:
      enable: true
      certManager: true
    worker:
      tolerations:
      - key: arm
        operator: Exists
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
      - key: "node-role.kubernetes.io/etcd"
        operator: "Exists"
      - effect: "NoExecute"
        operator: "Exists"
      - effect: "NoSchedule"
        operator: "Exists"
    master:
      replicaCount: 1
      tolerations:
      - key: arm
        operator: Exists
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
    topologyUpdater:
      enabled: true
      createCRD: true
      tolerations:
      - key: arm
        operator: Exists
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
      - key: "node-role.kubernetes.io/etcd"
        operator: "Exists"
      - effect: "NoExecute"
        operator: "Exists"
      - effect: "NoSchedule"
        operator: "Exists"
