apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vaultwarden-admin-token
spec:
  refreshInterval: "1m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: vaultwarden-admin-token
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ADMIN_TOKEN: "{{ .adminToken }}"
        PUSH_INSTALLATION_ID: "{{ .pushInstallationId }}"
        PUSH_INSTALLATION_KEY: "{{ .pushInstallationKey }}"
        PUSH_RELAY_URL: "https://api.bitwarden.com"
        PUSH_IDENTITY_URI: "https://identity.bitwarden.com"
  data:
    - secretKey: "adminToken"
      remoteRef:
        # metadataPolicy: Fetch
        key: "vaultwarden-admin-token"
        property: "admin-token"
    - secretKey: "pushInstallationId"
      remoteRef:
        # metadataPolicy: Fetch
        key: "vaultwarden-admin-token"
        property: "installation-id"
    - secretKey: "pushInstallationKey"
      remoteRef:
        # metadataPolicy: Fetch
        key: "vaultwarden-admin-token"
        property: "installation-key"
