apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vaultwarden-admin-token
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: vaultwarden-admin-token
    creationPolicy: Owner
  data:
    - secretKey: "ADMIN_TOKEN"
      remoteRef:
        metadataPolicy: Fetch
        key: "secret/vaultwarden-admin-token"
        property: "admin-token"
