apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vaultwarden-admin-token
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: vaultwarden-admin-token
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: admin-token
