---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vaultwarden
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        strategy: Recreate
        containers:
          main:
            securityContext:
              runAsUser: 1000
              runAsGroup: 1000

            image:
              # renovate: repository=vaultwarden/server
              repository: vaultwarden/server
              tag: 1.33.2
              pullPolicy: IfNotPresent

            # -- environment variables.
            # See [image docs](https://github.com/dani-garcia/vaultwarden/blob/main/.env.template) for more details.
            env:
              # -- Config dir
              DATA_FOLDER: "/config"
              DOMAIN: "https://vaultwarden.homelab.heyser.xyz"
              SIGNUPS_ALLOWED: "false"
              UID: 1000
              GID: 1000
              PUID: 1000
              PGID: 1000

            envFrom:
              - secretRef:
                  name: vaultwarden-admin-token
                  optional: false
        pod:
          securityContext:
            fsGroup: 1000
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups: [568,911,1001]
                
    # -- Configures service settings for the chart.
    service:
      main:
        annotations:
          traefik.ingress.kubernetes.io/service.nativelb: "true"
        controller: main
        ports:
          http:
            port: 80
          websocket:
            enabled: true
            port: 3012

    ingress:
      main:
        className: 'traefik'
        # -- Enable and configure ingress settings for the chart under this key.
        annotations:
          kubernetes.io/ingress.class: traefik
          traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
          # traefik.ingress.kubernetes.io/router.middlewares: "network-system-authentik@kubernetescrd"
        hosts:
          - host: &host "vaultwarden.homelab.heyser.xyz"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: http
              - path: /admin
                pathType: Prefix
                service:
                  identifier: main
                  port: http
              - path: /notifications/hub/negotiate
                pathType: Prefix
                service:
                  identifier: main
                  port: http
              - path: /notifications/hub
                pathType: Prefix
                service:
                  identifier: main
                  port: websocket
        tls:
          - hosts:
              - *host
            secretName: vaultwarden-homelab-heyser-xyz-tls

    route:
      # -- Enable and configure route settings for the chart under this key.
      main:
        parentRefs:
          - name: gateway
            namespace: gateway-namespace
            sectionName: gateway-section
        hostnames:
          - *host
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /
            backendRefs:
              - kind: Service
                port: 80
                name: main
                namespace: default
                weight: 1
          - matches:
              - path:
                  type: PathPrefix
                  value: /admin
            backendRefs:
              - kind: Service
                port: 80
                name: main
                namespace: default
                weight: 1
          - matches:
              - path:
                  type: PathPrefix
                  value: /notifications/hub/negotiate
            backendRefs:
              - kind: Service
                port: 80
                name: main
                namespace: default
                weight: 1
          - matches:
              - path:
                  type: PathPrefix
                  value: /notifications/hub
            backendRefs:
              - kind: Service
                port: 3012
                name: main
                namespace: default
                weight: 1

    # -- Configure persistence settings for the chart under this key.
    persistence:
      config:
        existingClaim: vaultwarden-config
        globalMounts:
          - path: /config
