apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mangayomi-server-mongo-data
  namespace: default
  annotations:
    nfs.io/storage-path: "containers/kubernetes/mangayomi-server/mongo/data"
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: "nfs-dynamic"
  resources:
    requests:
      storage: 10Gi
---
