apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mangayomi-server-secret-key
spec:
  refreshInterval: "1m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: mangayomi-server-secret-key
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        SECRET_KEY: "{{ .secretKey }}"
  data:
    - secretKey: "secretKey"
      remoteRef:
        # metadataPolicy: Fetch
        key: "mangayomi-server-secret-key"
        property: "secret-key"
