name: renovate

on:
  workflow_dispatch:
  schedule:
  - cron: '0 */6 * * *'

permissions:
  contents: read

jobs:
  helm-releases:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      attestations: write
      checks: write
      contents: write
      deployments: write
      discussions: write
      issues: write
      packages: write
      pages: write
      pull-requests: write
      repository-projects: write
      security-events: write
      statuses: write
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
      with:
        egress-policy: audit

    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      with:
        token: ${{ secrets.PAT }}
        fetch-depth: 1
        ref: main

    # - name: Install yq
    #   run: |
    #     sudo wget -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.44.3/yq_linux_amd64
    #     sudo chmod +x /usr/local/bin/yq

    - uses: step-security/setup-yq@ad0cf3bb7054291a414b615c1160ce0af1193a26 # v1.0.1

    - name: Create pull request for HelmRelease annotations
      uses: peter-evans/create-pull-request@6cd32fd93684475c31847837f87bb135d40a2b79 # v7
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: helm-release-annotations
        title: "[renovate] create helmrelease annotations [ci-skip]"
        signoff: true
        committer: "Ryan Heyser <1079612+rumblpak@users.noreply.github.com>"
        author: "Ryan Heyser <1079612+rumblpak@users.noreply.github.com>"
        commit-message: Create renovatebot helmrelease annotations
        body: |
          Signed-off-by: Ryan Heyser <1079612+rumblpak@users.noreply.github.com>
        labels: renovate/helm-release-annotations
