---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: qbittorrent-homelab-heyser-xyz
spec:
  subject:
    organizations:
    - Heyser
  secretName: qbittorrent-homelab-heyser-xyz-tls
  dnsNames:
  - qbittorrent.homelab.heyser.xyz
  issuerRef:
    name: letsencrypt-prod
    # We can reference ClusterIssuers by changing the kind here.
    # The defaultt value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: seedbox-homelab-heyser-xyz
spec:
  subject:
    organizations:
    - Heyser
  secretName: seedbox-homelab-heyser-xyz-tls
  dnsNames:
  - seedbox.homelab.heyser.xyz
  issuerRef:
    name: letsencrypt-prod
    # We can reference ClusterIssuers by changing the kind here.
    # The defaultt value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer
    group: cert-manager.io

---