apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: seedbox
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      annotations:
        k8s.v1.cni.cncf.io/networks: "seedbox-vpn"
    image:
      # renovate: repository=ghcr.io/onedr0p/qbittorrent
      repository: ghcr.io/onedr0p/qbittorrent
      tag: 4.6.5
    env:
      TZ: America/New_York
      QBITTORRENT__PORT: &port 80
      QBITTORRENT__BT_PORT: &port-bt 6882
    service:
      main:
        annotations:
          metallb.universe.tf/allow-shared-ip: "qbittorrent-share"
          metallb.universe.tf/address-pool: "default"
        ports:
          http:
            port: *port
      bittorrent:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: 10.0.101.5
        annotations:
          metallb.universe.tf/allow-shared-ip: "qbittorrent-share"
          metallb.universe.tf/address-pool: "default"
        ports:
          bittorrent:
            enabled: true
            port: *port-bt
            protocol: TCP
            targetPort: *port-bt
        externalTrafficPolicy: Local
    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        # ingressClassName: nginx
        # annotations:
          # nginx.ingress.kubernetes.io/auth-url: "https://auth.homelab.heyser.xyz/oauth2/auth"
          # nginx.ingress.kubernetes.io/auth-signin: https://auth.homelab.heyser.xyz/oauth2/start
        hosts:
        - host: &host seedbox.homelab.heyser.xyz
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - *host
        - secretName: seedbox-homelab-heyser-xyz-tls
    podSecurityContext:
      runAsUser: 1001
      runAsGroup: 1001
      fsGroup: 1001
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups: [568]
    # Note: If downloading very large torrents it might be worth using NFS for your download directory.
    # Beware if you are downloading torrents directly to a ZFS dataset that dataset will accrue fragmentation.
    persistence:
      config:
        enabled: true
        existingClaim: seedbox-config
      downloads:
        enabled: true
        existingClaim: seedbox-downloads
      media:
        enabled: true
        existingClaim: seedbox-media
      incomplete:
        enabled: true
        type: emptyDir
    resources:
      requests:
        cpu: 10m
        memory: 250Mi
      limits:
        memory: 2Gi
    tolerations:
    - key: "arm"
      operator: "Exists"
