---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qbittorrent-tailscale
spec:
  defaultBackend:
    service:
      name: qbittorrent-main
      port:
        number: 80
  ingressClassName: tailscale
  tls:
    - hosts:
        - qbittorrent
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: seedbox-tailscale
spec:
  defaultBackend:
    service:
      name: seedbox-main
      port:
        number: 80
  ingressClassName: tailscale
  tls:
    - hosts:
        - seedbox
---
