---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: qbittorrent-vpn
spec:
  config: '{
    "plugins": [{
      "name": "vpnnet1",
      "type": "bridge",
      "bridge": "vpnbr",
      "ipam": {
        "type": "static",
        "addresses": [{
          "address": "10.99.1.1/18",
          "gateway": "19.99.0.1"
        }],
        "routes": [{
          "dst": "0.0.0.0/0",
          "gw": "19.99.0.1"
        }],
        "dns": {
          "nameservers": ["10.99.0.1", "194.242.2.2"]
        }
      },{
        "type": "sbr"
      }]
    }'
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: seedbox-vpn
spec:
  config: '{
    "plugins": [{
      "name": "vpnnet1",
      "type": "bridge",
      "bridge": "vpnbr",
      "ipam": {
        "type": "dhcp"
        }
      },{
        "type": "sbr"
      }]
    }'
---
